/*
 @license EaselJS
 Visit http://createjs.com/ for documentation, updates and examples.

 Copyright (c) 2011-2015 gskinner.com, inc.

 Distributed under the terms of the MIT license.
 http://www.opensource.org/licenses/mit-license.html

 This notice shall be included in all copies or substantial portions of the Software.
*/
let createjs = {};
createjs.extend=function(g,e){function a(){this.constructor=g}return a.prototype=e.prototype,g.prototype=new a};createjs.C=function(g,e){var a=g.prototype,b=Object.getPrototypeOf&&Object.getPrototypeOf(a)||a.__proto__;if(b){a[(e+="_")+"constructor"]=b.constructor;for(var c in b)a.hasOwnProperty(c)&&"function"==typeof b[c]&&(a[e+c]=b[c])}return g};createjs.indexOf=function(g,e){for(var a=0,b=g.length;b>a;a++)if(e===g[a])return a;return-1};
(function(){function g(){throw"UID cannot be instantiated";}g.Pi=0;g.get=function(){return g.Pi++};createjs.Nh=g})();createjs.ka=function(g,e){return function(){var a="Deprecated property or method '"+e+"'. See docs for info.";return console&&(console.warn?console.warn(a):console.log(a)),g&&g.apply(this,arguments)}};
(function(){function g(a,b,c){this.type=a;this.currentTarget=this.target=null;this.eventPhase=0;this.bubbles=!!b;this.cancelable=!!c;this.timeStamp=(new Date).getTime();this.qd=this.Ce=this.oc=this.defaultPrevented=!1}var e=g.prototype;e.preventDefault=function(){this.defaultPrevented=this.cancelable&&!0};e.stopPropagation=function(){this.oc=!0};e.stopImmediatePropagation=function(){this.Ce=this.oc=!0};e.remove=function(){this.qd=!0};e.clone=function(){return new g(this.type,this.bubbles,this.cancelable)};
e.set=function(a){for(var b in a)this[b]=a[b];return this};e.toString=function(){return"[Event (type="+this.type+")]"};createjs.Event=g})();
(function(){function g(){this.ya=this.ea=null}var e=g.prototype;g.nc=function(a){a.addEventListener=e.addEventListener;a.Ne=e.Ne;a.removeEventListener=a.Ke=e.removeEventListener;a.pd=e.pd;a.sa=e.sa;a.dispatchEvent=e.dispatchEvent;a.lb=e.lb;a.Yg=e.Yg};e.addEventListener=function(a,b,c){var d=c?this.ya=this.ya||{}:this.ea=this.ea||{};var f=d[a];return f&&this.removeEventListener(a,b,c),f=d[a],f?f.push(b):d[a]=[b],b};e.Ne=function(a,b,c,d,f,h){return b.handleEvent&&(c=c||b,b=b.handleEvent),c=c||this,
this.addEventListener(a,function(k){b.call(c,k,f);d&&k.remove()},h)};e.removeEventListener=function(a,b,c){if(c=c?this.ya:this.ea){var d=c[a];if(d)for(var f=0,h=d.length;h>f;f++)if(d[f]==b){1==h?delete c[a]:d.splice(f,1);break}}};e.Ke=e.removeEventListener;e.pd=function(a){a?(this.ea&&delete this.ea[a],this.ya&&delete this.ya[a]):this.ea=this.ya=null};e.dispatchEvent=function(a,b,c){if("string"==typeof a){var d=this.ea;if(!(b||d&&d[a]))return!0;a=new createjs.Event(a,b,c)}else a.target&&a.clone&&
(a=a.clone());try{a.target=this}catch(f){}if(a.bubbles&&this.parent){c=this;for(b=[c];c.parent;)b.push(c=c.parent);d=b.length;for(c=d-1;0<=c&&!a.oc;c--)b[c].lb(a,1+(0==c));for(c=1;d>c&&!a.oc;c++)b[c].lb(a,3)}else this.lb(a,2);return!a.defaultPrevented};e.sa=function(a){var b=this.ea,c=this.ya;return!!(b&&b[a]||c&&c[a])};e.Yg=function(a){for(var b=this;b;){if(b.sa(a))return!0;b=b.parent}return!1};e.toString=function(){return"[EventDispatcher]"};e.lb=function(a,b){var c,d,f=2>=b?this.ya:this.ea;if(a&&
f&&(d=f[a.type])&&(c=d.length)){try{a.currentTarget=this}catch(k){}try{a.eventPhase=0|b}catch(k){}a.qd=!1;d=d.slice();for(f=0;c>f&&!a.Ce;f++){var h=d[f];h.handleEvent?h.handleEvent(a):h(a);a.qd&&(this.Ke(a.type,h,1==b),a.qd=!1)}}2===b&&this.lb(a,2.1)};createjs.wc=g})();
(function(){function g(){throw"Ticker cannot be instantiated.";}g.Dh="synched";g.hf="raf";g.TIMEOUT="timeout";g.Ik=null;g.ek=0;g.paused=!1;g.removeEventListener=null;g.pd=null;g.dispatchEvent=null;g.sa=null;g.ea=null;createjs.wc.nc(g);g.$h=g.addEventListener;g.addEventListener=function(){return!g.Zb&&g.fd(),g.$h.apply(g,arguments)};g.Zb=!1;g.Tc=0;g.dc=0;g.ig=0;g.Ri=0;g.rb=50;g.Aa=0;g.Cb=null;g.jc=null;g.qa=null;g.be=!0;g.de=function(b){g.rb=b;g.Zb&&g.Rc()};g.setInterval=createjs.ka(g.de,"Ticker.setInterval");
g.pi=function(){return g.rb};g.Vi=function(b){g.de(1E3/b)};g.ni=function(){return 1E3/g.rb};try{Object.defineProperties(g,{interval:{get:g.pi,set:g.de},framerate:{get:g.ni,set:g.Vi}})}catch(b){console.log(b)}g.fd=function(){g.Zb||(g.Zb=!0,g.Cb=[],g.jc=[],g.Tc=g.Wb(),g.Cb.push(g.Aa=0),g.interval=g.rb)};g.reset=function(){if(g.be){var b=window.cancelAnimationFrame||window.webkitCancelAnimationFrame||window.mozCancelAnimationFrame||window.oCancelAnimationFrame||window.msCancelAnimationFrame;b&&b(g.qa)}else clearTimeout(g.qa);
g.pd("tick");g.qa=g.Cb=g.jc=null;g.Tc=g.Aa=g.ig=g.dc=0;g.Zb=!1};g.getTime=function(b){return g.Tc?g.Wb()-(b?g.dc:0):-1};g.Ei=function(){g.qa=null;g.Rc();g.Wb()-g.Aa>=.97*(g.rb-1)&&g.fa()};g.Di=function(){g.qa=null;g.Rc();g.fa()};g.Fi=function(){g.qa=null;g.Rc();g.fa()};g.Rc=function(){if(null==g.qa){var b=g.Ik;if(b==g.Dh||b==g.hf){var c=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame;if(c){g.qa=
c(b==g.hf?g.Di:g.Ei);g.be=!0;return}}g.be=!1;g.qa=setTimeout(g.Fi,g.rb)}};g.fa=function(){var b=g.paused,c=g.Wb(),d=c-g.Aa;if(g.Aa=c,g.ig++,b&&(g.Ri++,g.dc+=d),g.sa("tick")){var f=new createjs.Event("tick"),h=g.ek;f.wg=h&&d>h?h:d;f.paused=b;f.time=c;f.vn=c-g.dc;g.dispatchEvent(f)}for(g.jc.unshift(g.Wb()-c);100<g.jc.length;)g.jc.pop();for(g.Cb.unshift(c);100<g.Cb.length;)g.Cb.pop()};var e=window,a=e.performance.now||e.performance.dn||e.performance.en||e.performance.jn||e.performance.webkitNow;g.Wb=
function(){return(a&&a.call(e.performance)||(new Date).getTime())-g.Tc};createjs.Il=g})();
(function(){function g(a){this.readyState=a.readyState;this.cj=a;this.wf=null;this.Aa=-1;2>this.readyState&&a.addEventListener("canplaythrough",this.dj.bind(this))}var e=g.prototype;e.Dg=function(){if(!(2>this.readyState)){var a=this.wf,b=this.cj;if(a||(a=this.wf=createjs.L?createjs.L():document.createElement("canvas"),a.width=b.videoWidth,a.height=b.videoHeight),2<=b.readyState&&b.currentTime!==this.Aa){var c=a.getContext("2d");c.clearRect(0,0,a.width,a.height);c.drawImage(b,0,0,a.width,a.height);
this.Aa=b.currentTime}return a}};e.dj=function(){this.readyState=2};createjs.Nl=g})();
(function(){function g(a,b,c,d,f,h,k,l,m,q,r){this.il(a,b,c);this.Qg=d;this.Rg=f;this.pc=null==m?d:m;this.qc=null==q?f:q;this.gk=h;this.Kg=k;this.nk=!!l;this.relatedTarget=r}var e=createjs.extend(g,createjs.Event);e.Wl=function(){return this.currentTarget.cd(this.pc,this.qc).x};e.Xl=function(){return this.currentTarget.cd(this.pc,this.qc).y};e.Vl=function(){return-1!==this.Kg};e.clone=function(){return new g(this.type,this.bubbles,this.cancelable,this.Qg,this.Rg,this.gk,this.Kg,this.nk,this.pc,this.qc)};
e.toString=function(){return"[MouseEvent (type="+this.type+" stageX="+this.Qg+" stageY="+this.Rg+")]"};createjs.MouseEvent=createjs.C(g,"Event")})();
(function(){function g(a,b,c,d,f,h){this.H(a,b,c,d,f,h)}var e=g.prototype;g.V=Math.PI/180;g.ca=null;e.H=function(a,b,c,d,f,h){return this.a=null==a?1:a,this.b=b||0,this.c=c||0,this.d=null==d?1:d,this.h=f||0,this.g=h||0,this};e.append=function(a,b,c,d,f,h){var k=this.a,l=this.b,m=this.c,q=this.d;return(1!=a||0!=b||0!=c||1!=d)&&(this.a=k*a+m*b,this.b=l*a+q*b,this.c=k*c+m*d,this.d=l*c+q*d),this.h=k*f+m*h+this.h,this.g=l*f+q*h+this.g,this};e.prepend=function(a,b,c,d,f,h){var k=this.a,l=this.c,m=this.h;
return this.a=a*k+c*this.b,this.b=b*k+d*this.b,this.c=a*l+c*this.d,this.d=b*l+d*this.d,this.h=a*m+c*this.g+f,this.g=b*m+d*this.g+h,this};e.Xc=function(a){this.append(a.a,a.b,a.c,a.d,a.h,a.g)};e.Ib=function(a){return this.prepend(a.a,a.b,a.c,a.d,a.h,a.g)};e.Yc=function(a,b,c,d,f,h,k,l,m){if(f%360){var q=f*g.V;f=Math.cos(q);q=Math.sin(q)}else f=1,q=0;return h||k?(h*=g.V,k*=g.V,this.append(Math.cos(k),Math.sin(k),-Math.sin(h),Math.cos(h),a,b),this.append(f*c,q*c,-q*d,f*d,0,0)):this.append(f*c,q*c,-q*
d,f*d,a,b),(l||m)&&(this.h-=l*this.a+m*this.c,this.g-=l*this.b+m*this.d),this};e.ln=function(a,b,c,d,f,h,k,l,m){if(f%360){var q=f*g.V;f=Math.cos(q);q=Math.sin(q)}else f=1,q=0;return(l||m)&&(this.h-=l,this.g-=m),h||k?(h*=g.V,k*=g.V,this.prepend(f*c,q*c,-q*d,f*d,0,0),this.prepend(Math.cos(k),Math.sin(k),-Math.sin(h),Math.cos(h),a,b)):this.prepend(f*c,q*c,-q*d,f*d,a,b),this};e.rotate=function(a){a*=g.V;var b=Math.cos(a);a=Math.sin(a);var c=this.a,d=this.b;return this.a=c*b+this.c*a,this.b=d*b+this.d*
a,this.c=-c*a+this.c*b,this.d=-d*a+this.d*b,this};e.Cn=function(a,b){return a*=g.V,b*=g.V,this.append(Math.cos(b),Math.sin(b),-Math.sin(a),Math.cos(a),0,0),this};e.scale=function(a,b){return this.a*=a,this.b*=a,this.c*=b,this.d*=b,this};e.translate=function(a,b){return this.h+=this.a*a+this.c*b,this.g+=this.b*a+this.d*b,this};e.ca=function(){return this.a=this.d=1,this.b=this.c=this.h=this.g=0,this};e.Ee=function(){var a=this.a,b=this.b,c=this.c,d=this.d,f=this.h,h=a*d-b*c;return this.a=d/h,this.b=
-b/h,this.c=-c/h,this.d=a/h,this.h=(c*this.g-d*f)/h,this.g=-(a*this.g-b*f)/h,this};e.isIdentity=function(){return 0===this.h&&0===this.g&&1===this.a&&0===this.b&&0===this.c&&1===this.d};e.Qj=function(a){return this.h===a.h&&this.g===a.g&&this.a===a.a&&this.b===a.b&&this.c===a.c&&this.d===a.d};e.transformPoint=function(a,b,c){return c=c||{},c.x=a*this.a+b*this.c+this.h,c.y=a*this.b+b*this.d+this.g,c};e.ym=function(a){null==a&&(a={});a.x=this.h;a.y=this.g;a.D=Math.sqrt(this.a*this.a+this.b*this.b);
a.F=Math.sqrt(this.c*this.c+this.d*this.d);var b=Math.atan2(-this.c,this.d),c=Math.atan2(this.b,this.a);return 1E-5>Math.abs(1-b/c)?(a.rotation=c/g.V,0>this.a&&0<=this.d&&(a.rotation+=0>=a.rotation?180:-180),a.skewX=a.skewY=0):(a.skewX=b/g.V,a.skewY=c/g.V),a};e.ga=function(a){return this.H(a.a,a.b,a.c,a.d,a.h,a.g)};e.clone=function(){return new g(this.a,this.b,this.c,this.d,this.h,this.g)};e.toString=function(){return"[Matrix2D (a="+this.a+" b="+this.b+" c="+this.c+" d="+this.d+" tx="+this.h+" ty="+
this.g+")]"};g.ca=new g;createjs.Ob=g})();
(function(){function g(a,b,c,d,f){this.H(a,b,c,d,f)}var e=g.prototype;e.H=function(a,b,c,d,f){return this.visible=null==a?!0:!!a,this.alpha=null==b?1:b,this.da=c,this.aa=d,this.l=f||this.l&&this.l.ca()||new createjs.Ob,this};e.append=function(a,b,c,d,f){return this.alpha*=b,this.da=c||this.da,this.aa=d||this.aa,this.visible=this.visible&&a,f&&this.l.Xc(f),this};e.prepend=function(a,b,c,d,f){return this.alpha*=b,this.da=this.da||c,this.aa=this.aa||d,this.visible=this.visible&&a,f&&this.l.Ib(f),this};
e.ca=function(){return this.visible=!0,this.alpha=1,this.da=this.aa=null,this.l.ca(),this};e.clone=function(){return new g(this.alpha,this.da,this.aa,this.visible,this.l.clone())};createjs.vd=g})();(function(){function g(a,b){this.H(a,b)}var e=g.prototype;e.H=function(a,b){return this.x=a||0,this.y=b||0,this};e.ga=function(a){return this.x=a.x,this.y=a.y,this};e.clone=function(){return new g(this.x,this.y)};e.toString=function(){return"[Point (x="+this.x+" y="+this.y+")]"};createjs.gf=g})();
(function(){function g(a,b,c,d){this.H(a,b,c,d)}var e=g.prototype;e.H=function(a,b,c,d){return this.x=a||0,this.y=b||0,this.width=c||0,this.height=d||0,this};e.extend=function(a,b,c,d){return c=c||0,d=d||0,a+c>this.x+this.width&&(this.width=a+c-this.x),b+d>this.y+this.height&&(this.height=b+d-this.y),a<this.x&&(this.width+=this.x-a,this.x=a),b<this.y&&(this.height+=this.y-b,this.y=b),this};e.jk=function(a,b,c,d){return this.x-=b,this.y-=a,this.width+=b+d,this.height+=a+c,this};e.ga=function(a){return this.H(a.x,
a.y,a.width,a.height)};e.contains=function(a,b,c,d){return c=c||0,d=d||0,a>=this.x&&a+c<=this.x+this.width&&b>=this.y&&b+d<=this.y+this.height};e.Ln=function(a){return this.clone().extend(a.x,a.y,a.width,a.height)};e.Tm=function(a){var b=a.x,c=a.y,d=b+a.width;a=c+a.height;return this.x>b&&(b=this.x),this.y>c&&(c=this.y),this.x+this.width<d&&(d=this.x+this.width),this.y+this.height<a&&(a=this.y+this.height),b>=d||c>=a?null:new g(b,c,d-b,a-c)};e.Um=function(a){return a.x<=this.x+this.width&&this.x<=
a.x+a.width&&a.y<=this.y+this.height&&this.y<=a.y+a.height};e.gd=function(){return 0>=this.width||0>=this.height};e.clone=function(){return new g(this.x,this.y,this.width,this.height)};e.toString=function(){return"[Rectangle (x="+this.x+" y="+this.y+" width="+this.width+" height="+this.height+")]"};createjs.wa=g})();
(function(){function g(a,b,c,d,f,h,k){a.addEventListener&&(this.target=a,this.Oe=null==c?"over":c,this.Jg=null==b?"out":b,this.yg=null==d?"down":d,this.play=f,this.Kc=!1,this.Td=!1,this.Ld=!1,a.He=!1,this.enabled=!0,this.handleEvent({}),h&&(k&&(h.kc=!1,h.$a&&h.$a(k)),a.ed=h))}var e=g.prototype;e.bg=function(a){if(a!=this.Ld){var b=this.target;(this.Ld=a)?(b.cursor="pointer",b.addEventListener("rollover",this),b.addEventListener("rollout",this),b.addEventListener("mousedown",this),b.addEventListener("pressup",
this),b.Sa&&(b.Bc=b.Sa,b.Sa=this.Sa)):(b.cursor=null,b.removeEventListener("rollover",this),b.removeEventListener("rollout",this),b.removeEventListener("mousedown",this),b.removeEventListener("pressup",this),b.Bc&&(b.Sa=b.Bc,delete b.Bc))}};e.Bn=createjs.ka(e.bg,"ButtonHelper.setEnabled");e.If=function(){return this.Ld};e.Jm=createjs.ka(e.If,"ButtonHelper.getEnabled");try{Object.defineProperties(e,{enabled:{get:e.If,set:e.bg}})}catch(a){}e.toString=function(){return"[ButtonHelper]"};e.handleEvent=
function(a){var b,c=this.target;a=a.type;"mousedown"==a?(this.Kc=!0,b=this.yg):"pressup"==a?(this.Kc=!1,b=this.Td?this.Oe:this.Jg):"rollover"==a?(this.Td=!0,b=this.Kc?this.yg:this.Oe):(this.Td=!1,b=this.Kc?this.Oe:this.Jg);this.play?c.dd&&c.dd(b):c.$a&&c.$a(b)};e.Sa=function(){var a=this.paused;this.Bc();this.paused=a};createjs.Yk=g})();
(function(){function g(a,b,c,d){this.color=a||"black";this.offsetX=b||0;this.offsetY=c||0;this.blur=d||0}var e=g.prototype;g.ca=new g("transparent",0,0,0);e.toString=function(){return"[Shadow]"};e.clone=function(){return new g(this.color,this.offsetX,this.offsetY,this.blur)};createjs.Al=g})();
(function(){function g(a){this.ef();this.complete=!0;this.framerate=0;this.K=this.Yb=this.u=this.ib=null;this.Xf=this.dg=this.$f=this.Zf=this.Mc=this.Md=this.Ef=this.Lc=0;this.Qi(a)}var e=createjs.extend(g,createjs.wc);e.Ff=function(){return this.ib.slice()};e.getAnimations=createjs.ka(e.Ff,"SpriteSheet.getAnimations");try{Object.defineProperties(e,{pg:{get:e.Ff}})}catch(a){}e.Xj=function(){return this.u?this.u.length:this.Mc||0};e.ue=function(a){return this.K[a]};e.Gb=function(a){var b;return this.u&&
(b=this.u[a])?b:null};e.Vj=function(a,b){var c=this.Gb(a);return c?(b||new createjs.wa).H(-c.N,-c.O,c.rect.width,c.rect.height):null};e.toString=function(){return"[SpriteSheet]"};e.clone=function(){throw"SpriteSheet cannot be cloned.";};e.Qi=function(a){var b,c;if(null!=a){if(this.framerate=a.framerate||0,a.images&&0<(c=a.images.length)){var d=this.Yb=[];for(b=0;c>b;b++){var f=a.images[b];if("string"==typeof f){var h=f;f=document.createElement("img");f.src=h}d.push(f);f.getContext||f.naturalWidth||
(this.Lc++,this.complete=!1,function(l){f.onload=function(){l.zi()}}(this,h),function(l,m){f.onerror=function(){l.yi(m)}}(this,h))}}if(null!=a.frames)if(Array.isArray(a.frames))for(this.u=[],d=a.frames,b=0,c=d.length;c>b;b++)h=d[b],this.u.push({image:this.Yb[h[4]?h[4]:0],rect:new createjs.wa(h[0],h[1],h[2],h[3]),N:h[5]||0,O:h[6]||0});else c=a.frames,this.Md=c.width,this.Ef=c.height,this.Zf=c.N||0,this.$f=c.O||0,this.dg=c.En||0,this.Xf=c.margin||0,this.Mc=c.count,0==this.Lc&&this.vf();if(this.ib=[],
null!=(c=a.pg)){this.K={};for(var k in c){a={name:k};h=c[k];if("number"==typeof h)d=a.frames=[h];else if(Array.isArray(h))if(1==h.length)a.frames=[h[0]];else for(a.speed=h[3],a.next=h[2],d=a.frames=[],b=h[0];b<=h[1];b++)d.push(b);else a.speed=h.speed,a.next=h.next,b=h.frames,d=a.frames="number"==typeof b?[b]:b.slice(0);!0!==a.next&&void 0!==a.next||(a.next=k);(!1===a.next||2>d.length&&a.next==k)&&(a.next=null);a.speed||(a.speed=1);this.ib.push(k);this.K[k]=a}}}};e.zi=function(){0==--this.Lc&&(this.vf(),
this.complete=!0,this.dispatchEvent("complete"))};e.yi=function(a){var b=new createjs.Event("error");b.src=a;this.dispatchEvent(b);0==--this.Lc&&this.dispatchEvent("complete")};e.vf=function(){if(!this.u&&0!=this.Md){this.u=[];var a=this.Mc||1E5,b=0,c=this.Md,d=this.Ef,f=this.dg,h=this.Xf,k=0,l=this.Yb;a:for(;k<l.length;k++)for(var m=l[k],q=m.width||m.naturalWidth,r=m.height||m.naturalHeight,n=h;r-h-d>=n;){for(var p=h;q-h-c>=p;){if(b>=a)break a;b++;this.u.push({image:m,rect:new createjs.wa(p,n,c,
d),N:this.Zf,O:this.$f});p+=c+f}n+=d+f}this.Mc=b}};createjs.Lh=createjs.C(g,"EventDispatcher")})();
(function(){function g(){this.Xd=this.Ta=this.Yd=this.Ua=this.Ca=this.Ya=null;this.ic=!1;this.mb=null;this.oa=[];this.Sb=0;this.La=[];this.kb=!1;this.Ab=0;this.clear()}var e=g.prototype;g.ah={Rk:0,Uk:1,Zk:2,gl:3,E:4,jl:5,ll:6,ml:7,nl:8,ol:9,pl:10,ql:11,rl:12,tl:13,ul:14,xl:15,Q:16,yl:17,zl:18,Hl:19,Ll:20,Ml:21,Ol:22,Pl:23,Ql:24,Rl:25,a:26,b:27,c:28,d:29,e:30,f:31,A:32,la:33,Be:34,Vm:35,k:36,ab:37,Zm:38,n:39,hn:40,p:41,q:42,r:43,wk:44,t:45,Kn:46,On:47,w:48,x:49,y:50,z:51,0:52,1:53,2:54,3:55,4:56,5:57,
6:58,7:59,8:60,9:61,"+":62,"/":63};g.Ih=["butt","round","square"];g.Jh=["miter","round","bevel"];var a=createjs.L?createjs.L():document.createElement("canvas");a.getContext&&(g.Jd=a.getContext("2d"),a.width=a.height=1);e.oi=function(){return this.Da(),this.oa};e.Km=createjs.ka(e.oi,"Graphics.getInstructions");e.gd=function(){return!(this.oa.length||this.La.length)};e.v=function(b,c){this.Da();for(var d=this.oa,f=this.Ab,h=d.length;h>f;f++)d[f].exec(b,c)};e.zg=function(b){this.Da();for(var c,d=this.oa,
f=this.Ab,h=d.length;h>f;f++)!1!==(c=d[f]).path&&c.exec(b)};e.moveTo=function(b,c){return this.append(new g.yh(b,c),!0)};e.lineTo=function(b,c){return this.append(new g.xh(b,c))};e.arcTo=function(b,c,d,f,h){return this.append(new g.$g(b,c,d,f,h))};e.arc=function(b,c,d,f,h,k){return this.append(new g.Zg(b,c,d,f,h,k))};e.quadraticCurveTo=function(b,c,d,f){return this.append(new g.Ch(b,c,d,f))};e.bezierCurveTo=function(b,c,d,f,h,k){return this.append(new g.dh(b,c,d,f,h,k))};e.rect=function(b,c,d,f){return this.append(new g.Rect(b,
c,d,f))};e.closePath=function(){return this.La.length?this.append(new g.nh):this};e.clear=function(){return this.oa.length=this.La.length=this.Sb=0,this.Ua=this.Yd=this.Ca=this.mb=this.Ta=this.Xd=null,this.kb=this.ic=!1,this};e.sg=function(b){return this.Pc(b?new g.Ha(b):null)};e.sj=function(b,c,d,f,h,k){return this.Pc((new g.Ha).jd(b,c,d,f,h,k))};e.uj=function(b,c,d,f,h,k,l,m){return this.Pc((new g.Ha).od(b,c,d,f,h,k,l,m))};e.pj=function(b,c,d){return this.Pc((new g.Ha(null,d)).Zc(b,c))};e.Oj=function(){return this.sg()};
e.Ck=function(b,c,d,f,h){return this.Da(!0),this.Ua=this.Ya=new g.Mh(b,c,d,f,h),this.Ca&&(this.Ca.Fa=h),this.ic=h,this};e.Bk=function(b,c){return this.Da(!0),this.Ta=this.Ya=new g.Cd(b,c),this};e.tg=function(b){return this.Qc(b?new g.zc(b):null)};e.tj=function(b,c,d,f,h,k){return this.Qc((new g.zc).jd(b,c,d,f,h,k))};e.vj=function(b,c,d,f,h,k,l,m){return this.Qc((new g.zc).od(b,c,d,f,h,k,l,m))};e.qj=function(b,c){return this.Qc((new g.zc).Zc(b,c))};e.Pj=function(){return this.tg()};e.um=e.quadraticCurveTo;
e.bd=e.rect;e.Lj=function(b,c,d,f,h){return this.Ag(b,c,d,f,h,h,h,h)};e.Ag=function(b,c,d,f,h,k,l,m){return this.append(new g.Gh(b,c,d,f,h,k,l,m))};e.Ij=function(b,c,d){return this.append(new g.mh(b,c,d))};e.Jj=function(b,c,d,f){return this.append(new g.th(b,c,d,f))};e.Kj=function(b,c,d,f,h,k){return this.append(new g.Bh(b,c,d,f,h,k))};e.append=function(b,c){return this.La.push(b),this.Ya=b,c||(this.kb=!0),this};e.Hj=function(b){for(var c=[this.moveTo,this.lineTo,this.quadraticCurveTo,this.bezierCurveTo,
this.closePath],d=[2,2,4,6,0],f=0,h=b.length,k=[],l=0,m=0,q=g.ah;h>f;){var r=b.charAt(f),n=q[r],p=n>>3,t=c[p];if(!t||3&n)throw"bad path data (@"+f+"): "+r;r=d[p];p||(l=m=0);k.length=0;f++;n=(n>>2&1)+2;for(p=0;r>p;p++){var x=q[b.charAt(f)],A=x>>5?-1:1;x=(31&x)<<6|q[b.charAt(f+1)];3==n&&(x=x<<6|q[b.charAt(f+2)]);x=A*x/10;p%2?l=x+=l:m=x+=m;k[p]=x;f+=n}t.apply(this,k)}return this};e.store=function(){return this.Da(!0),this.Ab=this.oa.length,this};e.Mn=function(){return this.Ab=0,this};e.clone=function(){var b=
new g;return b.Ya=this.Ya,b.Ca=this.Ca,b.Ua=this.Ua,b.Ta=this.Ta,b.ic=this.ic,b.mb=this.mb,b.oa=this.oa.slice(),b.Sb=this.Sb,b.La=this.La.slice(),b.kb=this.kb,b.Ab=this.Ab,b};e.toString=function(){return"[Graphics]"};e.gn=e.moveTo;e.Ym=e.lineTo;e.lm=e.arcTo;e.om=e.bezierCurveTo;e.nn=e.quadraticCurveTo;e.a=e.arc;e.r=e.rect;e.tm=e.closePath;e.c=e.clear;e.f=e.sg;e.Wm=e.sj;e.sn=e.uj;e.mm=e.pj;e.Am=e.Oj;e.Fn=e.Ck;e.xn=e.Bk;e.wk=e.tg;e.Xm=e.tj;e.un=e.vj;e.nm=e.qj;e.Cm=e.Pj;e.zm=e.bd;e.tn=e.Lj;e.qn=e.Ag;
e.wm=e.Ij;e.xm=e.Jj;e.dp=e.Kj;e.p=e.Hj;e.Da=function(b){var c=this.oa,d=this.La,f=this.Sb;if(this.kb&&d.length){c.length=f;c.push(g.rj);f=d.length;var h=c.length;c.length=h+f;for(var k=0;f>k;k++)c[k+h]=d[k];this.mb&&c.push(this.mb);this.Ca&&(this.Ta!==this.Xd&&c.push(this.Ta),this.Ua!==this.Yd&&c.push(this.Ua),b&&(this.Yd=this.Ua,this.Xd=this.Ta),c.push(this.Ca));this.kb=!1}b&&(d.length=0,this.Sb=c.length)};e.Pc=function(b){return this.Da(!0),this.Ya=this.mb=b,this};e.Qc=function(b){return this.Da(!0),
(this.Ya=this.Ca=b)&&(b.Fa=this.ic),this};(g.xh=function(b,c){this.x=b;this.y=c}).prototype.exec=function(b){b.lineTo(this.x,this.y)};(g.yh=function(b,c){this.x=b;this.y=c}).prototype.exec=function(b){b.moveTo(this.x,this.y)};(g.$g=function(b,c,d,f,h){this.Ze=b;this.$e=c;this.Ok=d;this.Qk=f;this.bb=h}).prototype.exec=function(b){b.arcTo(this.Ze,this.$e,this.Ok,this.Qk,this.bb)};(g.Zg=function(b,c,d,f,h,k){this.x=b;this.y=c;this.bb=d;this.Fk=f;this.Nj=h;this.nj=!!k}).prototype.exec=function(b){b.arc(this.x,
this.y,this.bb,this.Fk,this.Nj,this.nj)};(g.Ch=function(b,c,d,f){this.Ej=b;this.Fj=c;this.x=d;this.y=f}).prototype.exec=function(b){b.quadraticCurveTo(this.Ej,this.Fj,this.x,this.y)};(g.dh=function(b,c,d,f,h,k){this.Aj=b;this.Bj=c;this.Cj=d;this.Dj=f;this.x=h;this.y=k}).prototype.exec=function(b){b.bezierCurveTo(this.Aj,this.Bj,this.Cj,this.Dj,this.x,this.y)};(g.Rect=function(b,c,d,f){this.x=b;this.y=c;this.w=d;this.la=f}).prototype.exec=function(b){b.rect(this.x,this.y,this.w,this.la)};(g.nh=function(){}).prototype.exec=
function(b){b.closePath()};(g.bh=function(){}).prototype.exec=function(b){b.beginPath()};e=(g.Ha=function(b,c){this.style=b;this.l=c}).prototype;e.exec=function(b){if(this.style){b.fillStyle=this.style;var c=this.l;c&&(b.save(),b.transform(c.a,c.b,c.c,c.d,c.h,c.g));b.fill();c&&b.restore()}};e.jd=function(b,c,d,f,h,k){for(var l=this.style=g.Jd.createLinearGradient(d,f,h,k),m=0,q=b.length;q>m;m++)l.addColorStop(c[m],b[m]);return l.Lg={zj:b,uk:c,Nk:d,Pk:f,Ze:h,$e:k,type:"linear"},this};e.od=function(b,
c,d,f,h,k,l,m){for(var q=this.style=g.Jd.createRadialGradient(d,f,h,k,l,m),r=0,n=b.length;n>r;r++)q.addColorStop(c[r],b[r]);return q.Lg={zj:b,uk:c,Nk:d,Pk:f,on:h,Ze:k,$e:l,pn:m,type:"radial"},this};e.Zc=function(b,c){if(b.naturalWidth||b.getContext||2<=b.readyState)(this.style=g.Jd.createPattern(b,c||"")).Lg={image:b,rn:c,type:"bitmap"};return this};e.path=!1;e=(g.zc=function(b,c){this.style=b;this.Fa=c}).prototype;e.exec=function(b){this.style&&(b.strokeStyle=this.style,this.Fa&&(b.save(),b.setTransform(1,
0,0,1,0,0)),b.stroke(),this.Fa&&b.restore())};e.jd=g.Ha.prototype.jd;e.od=g.Ha.prototype.od;e.Zc=g.Ha.prototype.Zc;e.path=!1;e=(g.Mh=function(b,c,d,f,h){this.width=b;this.$c=c;this.hd=d;this.miterLimit=f;this.Fa=h}).prototype;e.exec=function(b){b.lineWidth=null==this.width?"1":this.width;b.lineCap=null==this.$c?"butt":isNaN(this.$c)?this.$c:g.Ih[this.$c];b.lineJoin=null==this.hd?"miter":isNaN(this.hd)?this.hd:g.Jh[this.hd];b.miterLimit=null==this.miterLimit?"10":this.miterLimit;b.Fa=null==this.Fa?
!1:this.Fa};e.path=!1;(g.Cd=function(b,c){this.xk=b;this.offset=c||0}).prototype.exec=function(b){b.setLineDash&&(b.setLineDash(this.xk||g.Cd.rh),b.lineDashOffset=this.offset||0)};g.Cd.rh=[];(g.Gh=function(b,c,d,f,h,k,l,m){this.x=b;this.y=c;this.w=d;this.la=f;this.sk=h;this.tk=k;this.rk=l;this.qk=m}).prototype.exec=function(b){var c=(r>q?q:r)/2,d=0,f=0,h=0,k=0,l=this.x,m=this.y,q=this.w,r=this.la,n=this.sk,p=this.tk,t=this.rk,x=this.qk;0>n&&(n*=d=-1);n>c&&(n=c);0>p&&(p*=f=-1);p>c&&(p=c);0>t&&(t*=
h=-1);t>c&&(t=c);0>x&&(x*=k=-1);x>c&&(x=c);b.moveTo(l+q-p,m);b.arcTo(l+q+p*f,m-p*f,l+q,m+p,p);b.lineTo(l+q,m+r-t);b.arcTo(l+q+t*h,m+r+t*h,l+q-t,m+r,t);b.lineTo(l+x,m+r);b.arcTo(l-x*k,m+r+x*k,l,m+r-x,x);b.lineTo(l,m+n);b.arcTo(l-n*d,m-n*d,l+n,m,n);b.closePath()};(g.mh=function(b,c,d){this.x=b;this.y=c;this.bb=d}).prototype.exec=function(b){b.arc(this.x,this.y,this.bb,0,2*Math.PI)};(g.th=function(b,c,d,f){this.x=b;this.y=c;this.w=d;this.la=f}).prototype.exec=function(b){var c=this.x,d=this.y,f=this.w,
h=this.la,k=f/2*.5522848,l=h/2*.5522848,m=c+f,q=d+h;f=c+f/2;h=d+h/2;b.moveTo(c,h);b.bezierCurveTo(c,h-l,f-k,d,f,d);b.bezierCurveTo(f+k,d,m,h-l,m,h);b.bezierCurveTo(m,h+l,f+k,q,f,q);b.bezierCurveTo(f-k,q,c,h+l,c,h)};(g.Bh=function(b,c,d,f,h,k){this.x=b;this.y=c;this.bb=d;this.Dk=f;this.kk=h;this.angle=k}).prototype.exec=function(b){var c=this.x,d=this.y,f=this.bb,h=(this.angle||0)/180*Math.PI,k=this.Dk,l=1-(this.kk||0),m=Math.PI/k;b.moveTo(c+Math.cos(h)*f,d+Math.sin(h)*f);for(var q=0;k>q;q++)h+=m,
1!=l&&b.lineTo(c+Math.cos(h)*f*l,d+Math.sin(h)*f*l),h+=m,b.lineTo(c+Math.cos(h)*f,d+Math.sin(h)*f);b.closePath()};g.rj=new g.bh;createjs.vh=g})();
(function(){function g(){this.ef();this.alpha=1;this.G=this.i=null;this.id=createjs.Nh.get();this.td=this.ld=!0;this.parent=this.name=null;this.rotation=this.O=this.N=0;this.F=this.D=1;this.skewY=this.skewX=0;this.da=null;this.visible=!0;this.y=this.x=0;this.aa=this.cb=null;this.Ue=!0;this.cursor=this.ed=this.ua=this.filters=null;this.Z=new createjs.vd;this.yb=new createjs.wa;this.Oa=null;this.Ea=g.Yh}var e=createjs.extend(g,createjs.wc);g.Wh="click dblclick mousedown mouseout mouseover pressmove pressup rollout rollover".split(" ");
g.Gk=!1;g.cg=!1;g.Yh=0;g.Zh=1;g.Xh=2;var a=createjs.L?createjs.L():document.createElement("canvas");a.getContext&&(g.Qd=a.getContext("2d"),a.width=a.height=1);e.Nf=function(){for(var b=this,c=createjs.lf;b.parent;)b=b.parent;return b instanceof c?b:null};e.Qm=createjs.ka(e.Nf,"DisplayObject.getStage");try{Object.defineProperties(e,{Jb:{get:e.Nf},ra:{get:function(){return this.G&&this.G.ra},set:function(b){this.G&&(this.G.ra=b)}},scale:{get:function(){return this.D},set:function(b){this.D=this.F=b}}})}catch(b){}e.isVisible=
function(){return!!(this.visible&&0<this.alpha&&0!=this.D&&0!=this.F)};e.v=function(b,c){var d=this.G;return d&&!c?d.v(b):!1};e.Xe=function(b){var c=this.ua,d=this.Z.l;c&&c.ba&&!c.ba.gd()&&(c.ha(d),b.transform(d.a,d.b,d.c,d.d,d.h,d.g),c.ba.zg(b),b.clip(),d.Ee(),b.transform(d.a,d.b,d.c,d.d,d.h,d.g));this.ha(d);c=d.h;var f=d.g;g.cg&&this.Ue&&(c=c+(0>c?-.5:.5)|0,f=f+(0>f?-.5:.5)|0);b.transform(d.a,d.b,d.c,d.d,c,f);b.globalAlpha*=this.alpha;this.aa&&(b.globalCompositeOperation=this.aa);this.da&&this.bi(b,
this.da)};e.cache=function(b,c,d,f,h,k){this.G||(this.G=new createjs.eh);this.G.define(this,b,c,d,f,h,k)};e.Lk=function(b){if(!this.G)throw"cache() must be called before updateCache()";this.G.update(b)};e.Vg=function(){this.G&&(this.G.release(),this.G=void 0)};e.Tj=function(){return this.G?this.G.Hm():null};e.kd=function(b,c,d){return this.we(this.Z.l).transformPoint(b,c,d||new createjs.gf)};e.cd=function(b,c,d){return this.we(this.Z.l).Ee().transformPoint(b,c,d||new createjs.gf)};e.dk=function(b,
c,d,f){return f=this.kd(b,c,f),d.cd(f.x,f.y,f)};e.setTransform=function(b,c,d,f,h,k,l,m,q){return this.x=b||0,this.y=c||0,this.D=null==d?1:d,this.F=null==f?1:f,this.rotation=h||0,this.skewX=k||0,this.skewY=l||0,this.N=m||0,this.O=q||0,this};e.ha=function(b){b=b&&b.ca()||new createjs.Ob;return this.cb?b.ga(this.cb):b.Yc(this.x,this.y,this.D,this.F,this.rotation,this.skewX,this.skewY,this.N,this.O)};e.we=function(b){var c=this;for(b=this.ha(b);c=c.parent;)b.Ib(c.ha(c.Z.l));return b};e.Cg=function(b){b=
b?b.ca():new createjs.vd;var c=this,d=c.ha(b.l);do b.prepend(c.visible,c.alpha,c.da,c.aa),c!=this&&d.Ib(c.ha(c.Z.l));while(c=c.parent);return b};e.Fg=function(b,c){var d=g.Qd;d.setTransform(1,0,0,1,-b,-c);this.v(d);var f=this.ee(d);return d.setTransform(1,0,0,1,0,0),d.clearRect(0,0,2,2),f};e.set=function(b){for(var c in b)this[c]=b[c];return this};e.M=function(){if(this.Oa)return this.yb.ga(this.Oa);var b=this.i;if(b){var c=this.Ul;return this.yb.H(this.Sl,this.Tl,b.width/c,b.height/c)}return null};
e.$j=function(){return this.nb()};e.yn=function(b,c,d,f){return null==b?void(this.Oa=b):void(this.Oa=(this.Oa||new createjs.wa).H(b,c,d,f))};e.clone=function(){return this.ja(new g)};e.toString=function(){return"[DisplayObject (name="+this.name+")]"};e.Db=null;e.ja=function(b){return b.alpha=this.alpha,b.ld=this.ld,b.td=this.td,b.name=this.name,b.N=this.N,b.O=this.O,b.rotation=this.rotation,b.D=this.D,b.F=this.F,b.da=this.da,b.skewX=this.skewX,b.skewY=this.skewY,b.visible=this.visible,b.x=this.x,
b.y=this.y,b.aa=this.aa,b.Ue=this.Ue,b.filters=null==this.filters?null:this.filters.slice(0),b.ua=this.ua,b.ed=this.ed,b.cursor=this.cursor,b.Oa=this.Oa,b};e.bi=function(b,c){c=c||Shadow.ca;b.shadowColor=c.color;b.shadowOffsetX=c.offsetX;b.shadowOffsetY=c.offsetY;b.shadowBlur=c.blur};e.fa=function(b){var c=this.ea;c&&c.Ve&&(b.target=null,b.oc=b.Ce=!1,this.dispatchEvent(b))};e.ee=function(b){try{var c=1<b.getImageData(0,0,1,1).data[3]}catch(d){if(!g.Gk)throw"An error has occurred. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images.";
}return c};e.nb=function(b,c){return this.ge(this.M(),b,c)};e.ge=function(b,c,d){if(!b)return b;var f=b.x,h=b.y,k=b.width,l=b.height,m=this.Z.l;m=d?m.ca():this.ha(m);(f||h)&&m.Yc(0,0,1,1,0,0,0,-f,-h);c&&m.Ib(c);c=k*m.a;k*=m.b;d=l*m.c;l*=m.d;var q=m.h;m=m.g;var r=q,n=q,p=m,t=m;return(f=c+q)<r?r=f:f>n&&(n=f),(f=c+d+q)<r?r=f:f>n&&(n=f),(f=d+q)<r?r=f:f>n&&(n=f),(h=k+m)<p?p=h:h>t&&(t=h),(h=k+l+m)<p?p=h:h>t&&(t=h),(h=l+m)<p?p=h:h>t&&(t=h),b.H(r,p,n-r,t-p)};e.Tf=function(){for(var b=g.Wh,c=0,d=b.length;d>
c;c++)if(this.sa(b[c]))return!0;return!!this.cursor};createjs.W=createjs.C(g,"EventDispatcher")})();
(function(){function g(){this.Kb();this.children=[];this.Hk=this.He=!0}var e=createjs.extend(g,createjs.W);e.si=function(){return this.children.length};e.Om=createjs.ka(e.si,"Container.getNumChildren");e.nc=g;e.isVisible=function(){var a=this.i||this.children.length;return!!(this.visible&&0<this.alpha&&0!=this.D&&0!=this.F&&a)};e.v=function(a,b){if(this.fb(a,b))return!0;for(var c=this.children.slice(),d=0,f=c.length;f>d;d++){var h=c[d];h.isVisible()&&(a.save(),h.Xe(a),h.v(a),a.restore())}return!0};
e.ng=function(a){if(null==a)return a;var b=arguments.length;if(1<b){for(var c=0;b>c;c++)this.ng(arguments[c]);return arguments[b-1]}b=a.parent;c=b===this;return b&&b.zb(createjs.indexOf(b.children,a),c),a.parent=this,this.children.push(a),c||a.dispatchEvent("added"),a};e.ne=function(a,b){var c=arguments.length,d=arguments[c-1];if(0>d||d>this.children.length)return arguments[c-2];if(2<c){for(var f=0;c-1>f;f++)this.ne(arguments[f],d+f);return arguments[c-2]}c=a.parent;d=c===this;return c&&c.zb(createjs.indexOf(c.children,
a),d),a.parent=this,this.children.splice(b,0,a),d||a.dispatchEvent("added"),a};e.removeChild=function(a){var b=arguments.length;if(1<b){for(var c=!0,d=0;b>d;d++)c=c&&this.removeChild(arguments[d]);return c}return this.zb(createjs.indexOf(this.children,a))};e.Og=function(a){var b=arguments.length;if(1<b){for(var c=[],d=0;b>d;d++)c[d]=arguments[d];c.sort(function(h,k){return k-h});var f=!0;for(d=0;b>d;d++)f=f&&this.zb(c[d]);return f}return this.zb(a)};e.Ng=function(){for(var a=this.children;a.length;)this.zb(0)};
e.Dm=function(a){return this.children[a]};e.Em=function(a){for(var b=this.children,c=0,d=b.length;d>c;c++)if(b[c].name==a)return b[c];return null};e.Dn=function(a){this.children.sort(a)};e.Fm=function(a){return createjs.indexOf(this.children,a)};e.In=function(a,b){var c=this.children,d=c[a],f=c[b];d&&f&&(c[a]=f,c[b]=d)};e.Hn=function(a,b){for(var c,d,f=this.children,h=0,k=f.length;k>h&&(f[h]==a&&(c=h),f[h]==b&&(d=h),null==c||null==d);h++);h!=k&&(f[c]=b,f[d]=a)};e.zn=function(a,b){var c=this.children,
d=c.length;if(!(a.parent!=this||0>b||b>=d)){for(var f=0;d>f&&c[f]!=a;f++);f!=d&&f!=b&&(c.splice(f,1),c.splice(b,0,a))}};e.contains=function(a){for(;a;){if(a==this)return!0;a=a.parent}return!1};e.Fg=function(a,b){return null!=this.Yj(a,b)};e.Pm=function(a,b,c){var d=[];a=this.kd(a,b);return this.Qa(a.x,a.y,d,0<c,1==c),d};e.Yj=function(a,b){var c=this.kd(a,b);return this.Qa(c.x,c.y,null,!1,!1)};e.M=function(){return this.nb(null,!0)};e.$j=function(){return this.nb()};e.clone=function(a){var b=this.ja(new g);
return a&&this.di(b),b};e.toString=function(){return"[Container (name="+this.name+")]"};e.fa=function(a){if(this.Hk)for(var b=this.children.length-1;0<=b;b--){var c=this.children[b];c.td&&c.fa&&c.fa(a)}this.cf(a)};e.di=function(a){a.children.length&&a.Ng();for(var b=a.children,c=0,d=this.children.length;d>c;c++){var f=this.children[c].clone(!0);f.parent=a;b.push(f)}};e.zb=function(a,b){if(0>a||a>this.children.length-1)return!1;var c=this.children[a];return c&&(c.parent=null),this.children.splice(a,
1),b||c.dispatchEvent("removed"),!0};e.Qa=function(a,b,c,d,f,h){if(h=h||0,!h&&!this.gg(this,a,b))return null;var k,l=createjs.W.Qd;f=f||d&&this.Tf();for(var m=this.children,q=m.length-1;0<=q;q--){var r=m[q],n=r.ed;if(r.visible&&(n||r.isVisible())&&(!d||r.ld)&&(n||this.gg(r,a,b)))if(!n&&r instanceof g){if(r=r.Qa(a,b,c,d,f,h+1),!c&&r)return d&&!this.He?this:r}else if(!d||f||r.Tf()){var p=r.Cg(r.Z);if(k=p.l,n&&(k.Xc(n.ha(n.Z.l)),p.alpha=n.alpha),l.globalAlpha=p.alpha,l.setTransform(k.a,k.b,k.c,k.d,k.h-
a,k.g-b),(n||r).v(l),this.ee(l)){if(l.setTransform(1,0,0,1,0,0),l.clearRect(0,0,2,2),!c)return d&&!this.He?this:r;c.push(r)}}}return null};e.gg=function(a,b,c){var d=a.ua;if(!d||!d.ba||d.ba.gd())return!0;var f=this.Z.l;f=(a=a.parent)?a.we(f):f.ca();f=d.ha(d.Z.l).Ib(f);a=createjs.W.Qd;return a.setTransform(f.a,f.b,f.c,f.d,f.h-b,f.g-c),d.ba.zg(a),a.fillStyle="#000",a.fill(),this.ee(a)?(a.setTransform(1,0,0,1,0,0),a.clearRect(0,0,2,2),!0):!1};e.nb=function(a,b){var c=this.vc();if(c)return this.ge(c,
a,b);var d=this.Z.l;d=b?d.ca():this.ha(d);a&&d.Ib(a);for(var f=this.children.length,h=null,k=0;f>k;k++){var l=this.children[k];l.visible&&(c=l.nb(d))&&(h?h.extend(c.x,c.y,c.width,c.height):h=c.clone())}return h};createjs.uc=createjs.C(g,"DisplayObject")})();
(function(){function g(a){this.bf();this.rg=!0;this.canvas="string"==typeof a?document.getElementById(a):a;this.nd=this.md=0;this.bd=null;this.Ie=this.Ek=!1;this.Ug=!0;this.Ig=!1;this.mk=!0;this.Zd={};this.ec=this.pa=this.$b=this.wb=null;this.Mj()}var e=createjs.extend(g,createjs.uc);e.Yl=function(){return this.pa};e.fm=function(a){this.pa&&(this.pa.ec=null);a&&(a.ec=this);this.pa=a};e.update=function(a){if(this.canvas&&(this.Ug&&this.Ve(a),!1!==this.dispatchEvent("drawstart",!1,!0))){createjs.W.cg=
this.Ek;a=this.bd;var b=this.canvas.getContext("2d");b.setTransform(1,0,0,1,0,0);this.rg&&(a?b.clearRect(a.x,a.y,a.width,a.height):b.clearRect(0,0,this.canvas.width+1,this.canvas.height+1));b.save();this.bd&&(b.beginPath(),b.rect(a.x,a.y,a.width,a.height),b.clip());this.Xe(b);this.v(b,!1);b.restore();this.dispatchEvent("drawend")}};e.Ve=function(a){if(this.td&&!1!==this.dispatchEvent("tickstart",!1,!0)){var b=new createjs.Event("tick");if(a)for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);this.fa(b);
this.dispatchEvent("tickend")}};e.handleEvent=function(a){"tick"==a.type&&this.update(a)};e.clear=function(){if(this.canvas){var a=this.canvas.getContext("2d");a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,this.canvas.width+1,this.canvas.height+1)}};e.toDataURL=function(a,b){var c=this.canvas.getContext("2d"),d=this.canvas.width,f=this.canvas.height;if(a){var h=c.getImageData(0,0,d,f);var k=c.globalCompositeOperation;c.globalCompositeOperation="destination-over";c.fillStyle=a;c.fillRect(0,0,d,f)}d=
this.canvas.toDataURL(b||"image/png");return a&&(c.putImageData(h,0,0),c.globalCompositeOperation=k),d};e.Bm=function(a){if(this.$b&&(clearInterval(this.$b),this.$b=null,0==a&&this.Vc(!0)),null==a)a=20;else if(0>=a)return;var b=this;this.$b=setInterval(function(){b.Vc()},1E3/Math.min(50,a))};e.Mj=function(){var a=!0;null==a&&(a=!0);var b,c=this.Cf;if(!a&&c){for(b in c)a=c[b],a.t.removeEventListener(b,a.f,!1);this.Cf=null}else if(a&&!c&&this.canvas){a=window.addEventListener?window:document;var d=
this;c=this.Cf={};c.cn={t:a,f:function(f){d.Ci(f)}};c.bn={t:a,f:function(f){d.Bi(f)}};c.vm={t:this.canvas,f:function(f){d.Pf(f)}};c.an={t:this.canvas,f:function(f){d.Ai(f)}};for(b in c)a=c[b],a.t.addEventListener(b,a.f,!1)}};e.clone=function(){throw"Stage cannot be cloned.";};e.toString=function(){return"[Stage (name="+this.name+")]"};e.mi=function(a){try{var b=a.getBoundingClientRect()}catch(f){b={top:a.offsetTop,left:a.offsetLeft,width:a.offsetWidth,height:a.offsetHeight}}var c=(window.pageXOffset||
document.scrollLeft||0)-(document.clientLeft||document.body.clientLeft||0),d=(window.pageYOffset||document.scrollTop||0)-(document.clientTop||document.body.clientTop||0);a=window.getComputedStyle?getComputedStyle(a,null):a.currentStyle;return{left:b.left+c+(parseInt(a.paddingLeft)+parseInt(a.borderLeftWidth)),right:b.right+c-(parseInt(a.paddingRight)+parseInt(a.borderRightWidth)),top:b.top+d+(parseInt(a.paddingTop)+parseInt(a.borderTopWidth)),bottom:b.bottom+d-(parseInt(a.paddingBottom)+parseInt(a.borderBottomWidth))}};
e.ob=function(a){var b=this.Zd[a];return b||(b=this.Zd[a]={x:0,y:0}),b};e.Bi=function(a){a||(a=window.event);this.Od(-1,a,a.pageX,a.pageY)};e.Od=function(a,b,c,d,f){if((!this.ec||void 0!==f)&&this.canvas){f=this.pa;var h=this.ob(a),k=h.mc;this.kg(a,b,c,d);(k||h.mc||this.Ig)&&(-1===a&&h.mc==!k&&this.T(this,k?"mouseleave":"mouseenter",!1,a,h,b),this.T(this,"stagemousemove",!1,a,h,b),this.T(h.target,"pressmove",!0,a,h,b));f&&f.Od(a,b,c,d,null)}};e.kg=function(a,b,c,d){var f=this.mi(this.canvas);c-=f.left;
d-=f.top;var h=this.canvas.width,k=this.canvas.height;c/=(f.right-f.left)/h;d/=(f.bottom-f.top)/k;f=this.ob(a);(f.mc=0<=c&&0<=d&&h-1>=c&&k-1>=d)?(f.x=c,f.y=d):this.Ig&&(f.x=0>c?0:c>h-1?h-1:c,f.y=0>d?0:d>k-1?k-1:d);f.lk=b;f.pc=c;f.qc=d;(a===this.wb||-1===a)&&(this.md=f.x,this.nd=f.y,this.Ie=f.mc)};e.Ci=function(a){this.Pd(-1,a,!1)};e.Pd=function(a,b,c,d){var f=this.pa,h=this.ob(a);if(!this.ec||void 0!==d){var k=null,l=h.target;d||!l&&!f||(k=this.Qa(h.x,h.y,null,!0));h.xg&&(this.T(this,"stagemouseup",
!1,a,h,b,k),h.xg=!1);k==l&&this.T(l,"click",!0,a,h,b);this.T(l,"pressup",!0,a,h,b);c?(a==this.wb&&(this.wb=null),delete this.Zd[a]):h.target=null;f&&f.Pd(a,b,c,d||k&&this)}};e.Ai=function(a){this.Nd(-1,a,a.pageX,a.pageY)};e.Nd=function(a,b,c,d,f){this.mk&&b.preventDefault();null!=this.wb&&-1!==a||(this.wb=a);null!=d&&this.kg(a,b,c,d);var h=null,k=this.pa,l=this.ob(a);f||(h=l.target=this.Qa(l.x,l.y,null,!0));l.mc&&(this.T(this,"stagemousedown",!1,a,l,b,h),l.xg=!0);this.T(h,"mousedown",!0,a,l,b);k&&
k.Nd(a,b,c,d,f||h&&this)};e.Vc=function(a,b,c){if(!this.ec||void 0!==b){var d=this.pa;if(!this.$b)return void(d&&d.Vc(a,b,c));var f=this.ob(-1);if(f&&(a||this.md!=this.Ni||this.nd!=this.Oi||!this.Ie)){var h,k=f.lk,l=c||k&&k.target==this.canvas,m=null,q=-1;var r="";!b&&(a||this.Ie&&l)&&(m=this.Qa(this.md,this.nd,null,!0),this.Ni=this.md,this.Oi=this.nd);var n=this.Mi||[],p=n[n.length-1],t=this.Mi=[];for(h=m;h;)t.unshift(h),r||(r=h.cursor),h=h.parent;this.canvas.style.cursor=r;!b&&c&&(c.canvas.style.cursor=
r);h=0;for(r=t.length;r>h&&t[h]==n[h];h++)q=h;p!=m&&this.T(p,"mouseout",!0,-1,f,k,m);for(h=n.length-1;h>q;h--)this.T(n[h],"rollout",!1,-1,f,k,m);for(h=t.length-1;h>q;h--)this.T(t[h],"rollover",!1,-1,f,k,p);p!=m&&this.T(m,"mouseover",!0,-1,f,k,p);d&&d.Vc(a,b||m&&this,c||l&&this)}}};e.Pf=function(a,b){var c=null,d=this.pa,f=this.ob(-1);b||(c=this.Qa(f.x,f.y,null,!0),this.T(c,"dblclick",!0,-1,f,a));d&&d.Pf(a,b||c&&this)};e.T=function(a,b,c,d,f,h,k){a&&(c||a.sa(b))&&(b=new createjs.MouseEvent(b,c,!1,
f.x,f.y,h,d,d===this.wb||-1===d,f.pc,f.qc,k),a.dispatchEvent(b))};createjs.lf=createjs.C(g,"Container")})();
(function(){function g(a,b){if(this.Fl(a),void 0!==b){if("object"!=typeof b)throw"Invalid options object";var c=b.kn,d=b.Kk,f=b.antialias,h=b.mn,k=b.qe}this.Ga=!1;this.Ti=h||!1;this.qf=f||!1;this.jg=d||!1;this.$d=c||!1;this.Pb=void 0;this.qe=k;this.Va=this.Wa=0;this.j=this.Oc=null;this.S={r:.5,A:.5,b:.5,a:0};this.Yf=g.ph;this.pf=this.Dd=this.hg=this.Rd=this.ie=this.je=this.ke=this.le=this.X=null;this.U=[];this.Bb={};this.R=[];this.Qb=[];this.J=8;this.Ud=-1;this.na=this.P=0;this.Sc=[];this.Ki=this.Jc=
0;this.Hb=!1;this.uf=new createjs.uc;this.Ii()}var e=createjs.extend(g,createjs.lf);g.xj=function(a,b){var c=!1;if(!a||!a.u)return null;void 0===b&&(b=-1);void 0===c&&(c=!1);var d=-1!=b&&c?b+1:a.u.length;for(c=-1!=b&&c?b:0;d>c;c++){var f=a.u[c];if(!(f.Ye||0>=f.image.width||0>=f.image.height)){var h=f.rect;f.Ye={t:h.y/f.image.height,ab:h.x/f.image.width,b:(h.y+h.height)/f.image.height,r:(h.x+h.width)/f.image.width}}}return a.u[-1!=b?b:0].Ye||{t:0,ab:0,b:1,r:1}};g.Ge=function(a){return a&&a instanceof
WebGLRenderingContext&&"undefined"!=typeof WebGLRenderingContext};g.yc=6;g.ph=1E4;g.Oh={t:0,ab:0,b:1,r:1};try{g.jh=new Float32Array([-1,1,1,1,-1,-1,1,1,1,-1,-1,-1]),g.hh=new Float32Array([0,0,1,0,0,1,1,0,1,1,0,1]),g.ih=new Float32Array([0,1,1,1,0,0,1,1,1,0,0,0])}catch(a){}g.jf="precision mediump float;varying vec2 vTextureCoord;varying lowp float indexPicker;varying lowp float alphaValue;";g.Ad=g.jf+"attribute vec2 vertexPosition;attribute vec2 uvPosition;attribute lowp float textureIndex;attribute lowp float objectAlpha;uniform mat4 pMatrix;";
g.yd=g.jf+"uniform sampler2D uSampler[{{count}}];";g.zd="void main(void) {gl_Position = vec4((vertexPosition.x * pMatrix[0][0]) + pMatrix[3][0],(vertexPosition.y * pMatrix[1][1]) + pMatrix[3][1],pMatrix[3][2],1.0);alphaValue = objectAlpha;indexPicker = textureIndex;vTextureCoord = uvPosition;}";g.xd="void main(void) {vec4 color = vec4(1.0, 0.0, 0.0, 1.0);if (indexPicker <= 0.5) {color = texture2D(uSampler[0], vTextureCoord);{{alternates}}}{{fragColor}}}";g.Eh="gl_FragColor = vec4(color.rgb, color.a * alphaValue);";
g.Fh="if(color.a > 0.0035) {gl_FragColor = vec4(color.rgb/color.a, color.a * alphaValue);} else {gl_FragColor = vec4(0.0, 0.0, 0.0, 0.0);}";g.Ah=g.zd;g.zh=g.xd;g.af="precision mediump float;varying highp vec2 vRenderCoord;varying highp vec2 vTextureCoord;";g.lh=g.af+"attribute vec2 vertexPosition;attribute vec2 uvPosition;uniform float uUpright;";g.gh=g.af+"uniform sampler2D uSampler;";g.kh="void main(void) {gl_Position = vec4(vertexPosition.x, vertexPosition.y, 0.0, 1.0);vRenderCoord = uvPosition;vTextureCoord = vec2(uvPosition.x, abs(uUpright - uvPosition.y));}";
g.fh="void main(void) {vec4 color = texture2D(uSampler, vRenderCoord);gl_FragColor = color;}";e.wi=function(){return!!this.j};e.Yi=function(a){a=isNaN(a)?1200:a;-1!=a&&(a=10>a?10:a);this.Pb=a};e.vi=function(){return Number(this.Pb)};try{Object.defineProperties(e,{ck:{get:e.wi},qe:{get:e.vi,set:e.Yi}})}catch(a){}e.Ii=function(){if(this.canvas){if(!this.j||this.j.canvas!==this.canvas){var a=this.j=this.ii(this.canvas,{depth:!1,alpha:this.jg,stencil:!0,antialias:this.qf,premultipliedAlpha:this.$d,preserveDrawingBuffer:this.Ti});
a&&(this.Mk(a.getParameter(a.MAX_TEXTURE_IMAGE_UNITS)),this.Vd=a.getParameter(a.MAX_COMBINED_TEXTURE_IMAGE_UNITS),this.fi(a),this.Hi(),a.disable(a.DEPTH_TEST),a.enable(a.BLEND),a.blendFuncSeparate(a.SRC_ALPHA,a.ONE_MINUS_SRC_ALPHA,a.ONE,a.ONE_MINUS_SRC_ALPHA),a.pixelStorei(a.UNPACK_PREMULTIPLY_ALPHA_WEBGL,this.$d),this.j.clearColor(this.S.r,this.S.A,this.S.b,this.S.a),this.eb(this.Wa||this.canvas.width,this.Va||this.canvas.height))}}else this.j=null};e.update=function(a){this.canvas&&((this.Ug&&this.Ve(a),
this.dispatchEvent("drawstart"),this.rg&&this.clear(),this.j)?(this.Rb(this,this.j),-1==this.Pb||this.na%(this.Pb/2|0)||this.pk(this.Pb)):(a=this.canvas.getContext("2d"),a.save(),this.Xe(a),this.v(a,!1),a.restore()),this.dispatchEvent("drawend"))};e.clear=function(){if(this.canvas)if(g.Ge(this.j)){var a=this.j,b=this.S,c=this.jg?b.a:1;this.j.clearColor(b.r*c,b.A*c,b.b*c,c);a.clear(a.COLOR_BUFFER_BIT);this.j.clearColor(b.r,b.A,b.b,b.a)}else this.El()};e.v=function(a,b){return a===this.j&&g.Ge(this.j)?
(this.Rb(this,this.j,b),!0):this.Gl(a,b)};e.yj=function(a,b,c){g.Ge(this.j)&&this.ci(this.j,a,b,c)};e.Mg=function(a,b){if(a>this.Vd||0>a)throw"Slot outside of acceptable range";this.Sc[a]=!!b};e.Za=function(a,b,c){var d,f=!1,h=this.j;if(void 0!==a.Ac&&a.Ac===a.xa&&(f=!0),f?(void 0===a.Ja?a.Ja=this.Eg(b,c):((b!=a.Ja.ej||c!=a.Ja.Gi)&&this.Te(a.Ja,b,c),this.ia(h)),d=a.Ja):(void 0===a.xa?a.xa=this.Eg(b,c):((b!=a.xa.ej||c!=a.xa.Gi)&&this.Te(a.xa,b,c),this.ia(h)),d=a.xa),!d)throw"Problems creating render textures, known causes include using too much VRAM by not releasing WebGL texture instances";
return a.Ac=d,d};e.Se=function(a){var b;if(a){if(a.children){var c=0;for(b=a.children.length;b>c;c++)this.Se(a.children[c])}a.i&&a.Vg();c=void 0;if(void 0!==a.B){if(a===this.U[a.B]){this.sb(a);a.B=void 0;return}c=a}else if(2===a.Ea)c=a.image;else if(1===a.Ea){c=0;for(b=a.m.Yb.length;b>c;c++)this.Se(a.m.Yb[c]);return}void 0===c?this.Ga&&console.log("No associated texture found on release"):(this.sb(this.U[c.B]),c.B=void 0)}};e.pk=function(a){void 0==a&&(a=100);for(var b=this.U,c=b.length,d=0;c>d;d++){var f=
b[d];f&&f.na+a<=this.na&&this.sb(f)}};e.Mk=function(a){var b=this.j,c=!1;(1>a||isNaN(a))&&(a=1);for(this.J=a;!c;)try{this.X=this.Df(b),c=!0}catch(d){if(1==this.J)throw"Cannot compile shader "+d;this.J-=4;1>this.J&&(this.J=1);this.Ga&&console.log("Reducing desired texture count due to errors: "+this.J)}};e.eb=function(a,b){this.Wa=0|a;this.Va=0|b;var c=this.j;c&&(c.viewport(0,0,this.Wa,this.Va),this.Oc=new Float32Array([2/this.Wa,0,0,0,0,-2/this.Va,1,0,0,0,1,0,-1,1,.1,0]),this.xb=new Float32Array([0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),this.xb.set(this.Oc),this.xb[5]*=-1,this.xb[13]*=-1)};e.xe=function(a){a||(a=this);var b=this.j,c=this.X;if(a.Gd)c=a.Gd,a.va&&(b.useProgram(c),a.va(b,this,c));else try{c=this.Df(b,"filter",a.Ph,a.gb,a.va&&a.va.bind(a)),a.Gd=c,c.bm=a.toString()}catch(d){console&&console.log("SHADER SWITCH FAILURE",d)}return c};e.ve=function(a,b){var c=this.j,d=c.createTexture();return this.Te(d,Math.ceil(0<a?a:1)||1,Math.ceil(0<b?b:1)||1),this.ia(c,!1),d};e.Te=function(a,b,c){var d=
this.j;d.bindTexture(d.TEXTURE_2D,a);d.texImage2D(d.TEXTURE_2D,0,d.RGBA,b,c,0,d.RGBA,d.UNSIGNED_BYTE,null);a.width=b;a.height=c};e.Eg=function(a,b){var c=this.j,d=this.ve(a,b);if(!d)return null;var f=c.createFramebuffer();return f?(d.width=a,d.height=b,c.bindFramebuffer(c.FRAMEBUFFER,f),c.framebufferTexture2D(c.FRAMEBUFFER,c.COLOR_ATTACHMENT0,c.TEXTURE_2D,d,0),f.em=d,d.Pa=f,d.B=this.U.length,this.U[d.B]=d,c.bindFramebuffer(c.FRAMEBUFFER,null),d):null};e.ia=function(a,b){b&&this.qf?(a.texParameteri(a.TEXTURE_2D,
a.TEXTURE_MIN_FILTER,a.LINEAR),a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR)):(a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.NEAREST),a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.NEAREST));a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE)};e.An=function(a){var b,c,d,f,h;"string"==typeof a?0==a.indexOf("#")?(4==a.length&&(a="#"+a.charAt(1)+a.charAt(1)+a.charAt(2)+a.charAt(2)+a.charAt(3)+a.charAt(3)),
b=Number("0x"+a.slice(1,3))/255,c=Number("0x"+a.slice(3,5))/255,d=Number("0x"+a.slice(5,7))/255,f=Number("0x"+a.slice(7,9))/255):0==a.indexOf("rgba(")&&(h=a.slice(5,-1).split(","),b=Number(h[0])/255,c=Number(h[1])/255,d=Number(h[2])/255,f=Number(h[3])):(b=((4278190080&a)>>>24)/255,c=((16711680&a)>>>16)/255,d=((65280&a)>>>8)/255,f=(255&a)/255);this.S.r=b||0;this.S.A=c||0;this.S.b=d||0;this.S.a=f||0;this.j&&this.j.clearColor(this.S.r,this.S.A,this.S.b,this.S.a)};e.toString=function(){return"[StageGL (name="+
this.name+")]"};e.ii=function(a,b){try{var c=a.getContext("webgl",b)||a.getContext("experimental-webgl",b)}catch(d){}c?(c.Rn=a.width,c.Qn=a.height):console.error?console.error("Could not initialize WebGL"):console.log("Could not initialize WebGL");return c};e.Df=function(a,b,c,d,f){a.useProgram(null);switch(b){case "filter":c=g.lh+(c||g.kh);d=g.gh+(d||g.fh);break;case "particle":c=g.Ad+g.Ah;d=g.yd+g.zh;break;case "override":c=g.Ad+(c||g.zd);d=g.yd+(d||g.xd);break;default:c=g.Ad+g.zd,d=g.yd+g.xd}c=
this.xf(a,a.VERTEX_SHADER,c);var h=this.xf(a,a.FRAGMENT_SHADER,d);d=a.createProgram();if(a.attachShader(d,c),a.attachShader(d,h),a.linkProgram(d),d.hm=b,!a.getProgramParameter(d,a.LINK_STATUS))throw a.useProgram(this.X),a.getProgramInfoLog(d);switch(a.useProgram(d),b){case "filter":d.tc=a.getAttribLocation(d,"vertexPosition");a.enableVertexAttribArray(d.tc);d.sc=a.getAttribLocation(d,"uvPosition");a.enableVertexAttribArray(d.sc);d.rd=a.getUniformLocation(d,"uSampler");a.uniform1i(d.rd,0);d.Wg=a.getUniformLocation(d,
"uUpright");a.uniform1f(d.Wg,0);f&&f(a,this,d);break;default:d.tc=a.getAttribLocation(d,"vertexPosition");a.enableVertexAttribArray(d.tc);d.sc=a.getAttribLocation(d,"uvPosition");a.enableVertexAttribArray(d.sc);d.Tg=a.getAttribLocation(d,"textureIndex");a.enableVertexAttribArray(d.Tg);d.og=a.getAttribLocation(d,"objectAlpha");a.enableVertexAttribArray(d.og);b=[];for(f=0;f<this.J;f++)b[f]=f;d.wn=b;d.rd=a.getUniformLocation(d,"uSampler");a.uniform1iv(d.rd,b);d.ik=a.getUniformLocation(d,"pMatrix")}return a.useProgram(this.X),
d};e.xf=function(a,b,c){c=c.replace(/{{count}}/g,this.J);for(var d="",f=1;f<this.J;f++)d+="} else if (indexPicker <= "+f+".5) { color = texture2D(uSampler["+f+"], vTextureCoord);";c=c.replace(/{{alternates}}/g,d);c=c.replace(/{{fragColor}}/g,this.$d?g.Fh:g.Eh);b=a.createShader(b);if(a.shaderSource(b,c),a.compileShader(b),!a.getShaderParameter(b,a.COMPILE_STATUS))throw a.getShaderInfoLog(b);return b};e.fi=function(a){var b,c=this.Yf*g.yc,d=this.ke=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,d);var f=
2;var h=this.le=new Float32Array(c*f);var k=0;for(b=h.length;b>k;k+=f)h[k]=h[k+1]=0;a.bufferData(a.ARRAY_BUFFER,h,a.DYNAMIC_DRAW);d.ta=f;d.Je=c;d=this.ie=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,d);f=2;h=this.je=new Float32Array(c*f);k=0;for(b=h.length;b>k;k+=f)h[k]=h[k+1]=0;a.bufferData(a.ARRAY_BUFFER,h,a.DYNAMIC_DRAW);d.ta=f;d.Je=c;d=this.hg=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,d);f=1;h=this.Rd=new Float32Array(c*f);k=0;for(b=h.length;b>k;k++)h[k]=0;a.bufferData(a.ARRAY_BUFFER,h,a.DYNAMIC_DRAW);
d.ta=f;d.Je=c;d=this.pf=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,d);f=1;h=this.Dd=new Float32Array(c*f);k=0;for(b=h.length;b>k;k++)h[k]=1;a.bufferData(a.ARRAY_BUFFER,h,a.DYNAMIC_DRAW);d.ta=f;d.Je=c};e.Hi=function(){this.Ud=-1;this.U=[];this.Bb={};this.Qb=[];this.R=[];for(var a=0;a<this.J;a++){var b=this.ve();if(this.Qb[a]=this.R[a]=b,!b)throw"Problems creating basic textures, known causes include using too much VRAM by not releasing WebGL texture instances";}};e.Li=function(a,b){var c=b.src;c||
(b.Ji=!0,c=b.src="canvas_"+this.Ki++);var d=this.Bb[c];void 0===d&&(d=this.Bb[c]=this.U.length);void 0===this.U[d]&&(this.U[d]=this.ve());(c=this.U[d])?(c.P=this.P,c.B=d,c.qb=b,this.Ic(a,c),b.B=d,b.complete||b.naturalWidth||b.Ji?this.Wc(a,b):b.addEventListener("load",this.Wc.bind(this,a,b))):(console.error&&console.error("Problem creating desired texture, known causes include using too much VRAM by not releasing WebGL texture instances")||console.log("Problem creating desired texture, known causes include using too much VRAM by not releasing WebGL texture instances"),
c=this.Qb[0],c.P=this.P,c.B=-1,c.qb=c,this.Ic(a,c));return c};e.Wc=function(a,b){var c=b.width&b.width-1||b.height&b.height-1,d=this.U[b.B];a.activeTexture(a.TEXTURE0+d.Ka);a.bindTexture(a.TEXTURE_2D,d);d.Fe=!c;this.ia(a,d.Fe);try{a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,b)}catch(f){console.error?(console.error("\nAn error has occurred. This is most likely due to security restrictions on WebGL images with local or cross-domain origins"),console.error(f)):console&&(console.log("\nAn error has occurred. This is most likely due to security restrictions on WebGL images with local or cross-domain origins"),
console.log(f))}b.Sd=!1;d.im=b.width;d.Zl=b.height;this.Ga&&(c&&console.warn("NPOT(Non Power of Two) Texture: "+b.src),(b.width>a.MAX_TEXTURE_SIZE||b.height>a.MAX_TEXTURE_SIZE)&&console&&console.error("Oversized Texture: "+b.width+"x"+b.height+" vs "+a.MAX_TEXTURE_SIZE+"max"))};e.Ic=function(a,b){if(this.R[b.Ka]!==b){var c=-1,d=(this.Ud+1)%this.J,f=d;do{if(this.R[f].P!=this.P&&!this.Sc[f]){c=f;break}f=(f+1)%this.J}while(f!==d);-1===c&&(this.re="textureOverflow",this.Tb(a),this.Xa=0,c=d);this.R[c]=
b;b.Ka=c;(d=b.qb)&&d.Sd&&void 0!==b.na?this.Wc(a,d):(a.activeTexture(a.TEXTURE0+c),a.bindTexture(a.TEXTURE_2D,b),this.ia(a));this.Ud=c}else d=b.qb,void 0!=b.B&&d&&d.Sd&&this.Wc(a,d);b.na=this.na;b.P=this.P};e.sb=function(a){if(a){var b=this.j;if(void 0!==a.B&&0<=a.B){this.U[a.B]=void 0;for(var c in this.Bb)this.Bb[c]==a.B&&delete this.Bb[c];a.qb&&(a.qb.B=void 0);a.qb=a.B=void 0}void 0!==a.Ka&&this.R[a.Ka]===a&&(this.R[a.Ka]=this.Qb[a.Ka]);try{a.Pa&&b.deleteFramebuffer(a.Pa),a.Pa=void 0}catch(d){this.Ga&&
console.log(d)}try{b.deleteTexture(a)}catch(d){this.Ga&&console.log(d)}}};e.sf=function(a){var b,c=this.j;this.Dc||(this.Dc=[]);void 0===b&&(b=this.Dc);for(var d=0;d<this.J;d++)c.activeTexture(c.TEXTURE0+d),a?this.R[d]=b[d]:(b[d]=this.R[d],this.R[d]=this.Qb[d]),c.bindTexture(c.TEXTURE_2D,this.R[d]),this.ia(c,this.R[d].Fe);a&&b===this.Dc&&(this.Dc=[])};e.Rb=function(a,b,c){0<this.Jc&&this.Tb(b);this.Jc++;this.na++;this.depth=this.Xa=0;this.rf(a,b,new createjs.Ob,this.alpha,c);this.re="drawFinish";
this.Tb(b);this.Jc--};e.ci=function(a,b,c,d){var f,h=this.X,k=this.Sc,l=this.Vd-1,m=this.Wa,q=this.Va;this.Mg(l,!0);var r=b.ha();r=r.clone();r.scale(1/d.scale,1/d.scale);r=r.Ee();r.translate(-d.Le/d.scale*b.D,-d.Me/d.scale*b.F);var n=this.uf;n.children=[b];n.cb=r;this.sf(!1);c&&c.length?this.gi(b,c,d):this.Hb?(a.clear(a.COLOR_BUFFER_BIT),this.Rb(n,a,!0)):(a.activeTexture(a.TEXTURE0+l),b.i=this.Za(b,d.s,d.o),f=b.i,a.bindFramebuffer(a.FRAMEBUFFER,f.Pa),this.eb(d.s,d.o),this.Oc=this.xb,a.clear(a.COLOR_BUFFER_BIT),
this.Rb(n,a,!0),a.bindFramebuffer(a.FRAMEBUFFER,null),this.eb(m,q));this.sf(!0);this.Mg(l,!1);this.X=h;this.Sc=k};e.gi=function(a,b,c){var d=this.j,f=this.Vd-1,h=this.Wa,k=this.Va,l=this.uf,m=b.length;d.activeTexture(d.TEXTURE0+f);var q=this.Za(a,c.s,c.o);d.bindFramebuffer(d.FRAMEBUFFER,q.Pa);this.eb(c.s,c.o);d.clear(d.COLOR_BUFFER_BIT);this.Rb(l,d,!0);d.activeTexture(d.TEXTURE0);d.bindTexture(d.TEXTURE_2D,q);this.ia(d);l=!1;var r=0,n=b[r];do(this.X=this.xe(n))&&(d.activeTexture(d.TEXTURE0+f),q=this.Za(a,
c.s,c.o),d.bindFramebuffer(d.FRAMEBUFFER,q.Pa),d.viewport(0,0,c.s,c.o),d.clear(d.COLOR_BUFFER_BIT),this.Kd(d,l),d.activeTexture(d.TEXTURE0),d.bindTexture(d.TEXTURE_2D,q),this.ia(d),(1<m||b[0].ac)&&(l=!l),n=null!==n.ac?n.ac:b[++r]);while(n);this.Hb?(d.bindFramebuffer(d.FRAMEBUFFER,null),this.eb(h,k),this.X=this.xe(this),d.clear(d.COLOR_BUFFER_BIT),this.Kd(d,l)):(l&&(d.activeTexture(d.TEXTURE0+f),q=this.Za(a,c.s,c.o),d.bindFramebuffer(d.FRAMEBUFFER,q.Pa),this.X=this.xe(this),d.viewport(0,0,c.s,c.o),
d.clear(d.COLOR_BUFFER_BIT),this.Kd(d,!l)),d.bindFramebuffer(d.FRAMEBUFFER,null),this.eb(h,k),a.i=q)};e.rf=function(a,b,c,d,f){a.Xb||(a.Xb=new createjs.Ob);var h=a.Xb;h.ga(c);a.cb?h.Xc(a.cb):h.Yc(a.x,a.y,a.D,a.F,a.rotation,a.skewX,a.skewY,a.N,a.O);var k,l,m,q;c=a.children.length;for(var r=0;c>r;r++){var n=a.children[r];if(n.visible&&d)if(n.i&&!f||(n.Db&&n.Db(),!n.children)){this.Xa+1>this.Yf&&(this.re="vertexOverflow",this.Tb(b),this.Xa=0);n.Xb||(n.Xb=new createjs.Ob);var p=n.Xb;p.ga(h);n.cb?p.Xc(n.cb):
p.Yc(n.x,n.y,n.D,n.F,n.rotation,n.skewX,n.skewY,n.N,n.O);var t,x,A,y,v=n.i&&!f;if(2===n.Ea||v)var z=(f?!1:n.i)||n.image;else{if(1!==n.Ea)continue;if(A=n.m.Gb(n.currentFrame),null===A)continue;z=A.image}var w=this.je,u=this.le,E=this.Rd,F=this.Dd;if(z){if(void 0===z.B){var B=this.Li(b,z);this.Ic(b,B)}else{if(B=this.U[z.B],!B){this.Ga&&console.log("Texture should not be looked up while not being stored.");continue}B.P!==this.P&&this.Ic(b,B)}(x=B.Ka,2===n.Ea||v)?!v&&n.ma?(n.mg||(n.mg={}),y=n.ma,t=n.mg,
t.t=y.y/z.height,t.ab=y.x/z.width,t.b=(y.y+y.height)/z.height,t.r=(y.x+y.width)/z.width,k=0,l=0,m=y.width+k,q=y.height+l):(t=g.Oh,v?(y=n.G,k=y.x+y.Ub/y.scale,l=y.y+y.Vb/y.scale,m=y.s/y.scale+k,q=y.o/y.scale+l):(k=0,l=0,m=z.width+k,q=z.height+l)):1===n.Ea&&(q=A.rect,(t=A.Ye)||(t=g.xj(n.m,n.currentFrame)),k=-A.N,l=-A.O,m=q.width-A.N,q=q.height-A.O);z=this.Xa*g.yc;v=2*z;u[v]=k*p.a+l*p.c+p.h;u[v+1]=k*p.b+l*p.d+p.g;u[v+2]=k*p.a+q*p.c+p.h;u[v+3]=k*p.b+q*p.d+p.g;u[v+4]=m*p.a+l*p.c+p.h;u[v+5]=m*p.b+l*p.d+
p.g;u[v+6]=u[v+2];u[v+7]=u[v+3];u[v+8]=u[v+4];u[v+9]=u[v+5];u[v+10]=m*p.a+q*p.c+p.h;u[v+11]=m*p.b+q*p.d+p.g;w[v]=t.ab;w[v+1]=t.t;w[v+2]=t.ab;w[v+3]=t.b;w[v+4]=t.r;w[v+5]=t.t;w[v+6]=t.ab;w[v+7]=t.b;w[v+8]=t.r;w[v+9]=t.t;w[v+10]=t.r;w[v+11]=t.b;E[z]=E[z+1]=E[z+2]=E[z+3]=E[z+4]=E[z+5]=x;F[z]=F[z+1]=F[z+2]=F[z+3]=F[z+4]=F[z+5]=n.alpha*d;this.Xa++}}else this.rf(n,b,h,n.alpha*d)}};e.Tb=function(a){if(!(0>=this.Xa)){this.Ga&&console.log("Draw["+this.na+":"+this.P+"] : "+this.re);var b=this.X,c=this.ke,d=
this.hg,f=this.ie,h=this.pf;a.useProgram(b);a.bindBuffer(a.ARRAY_BUFFER,c);a.vertexAttribPointer(b.tc,c.ta,a.FLOAT,!1,0,0);a.bufferSubData(a.ARRAY_BUFFER,0,this.le);a.bindBuffer(a.ARRAY_BUFFER,d);a.vertexAttribPointer(b.Tg,d.ta,a.FLOAT,!1,0,0);a.bufferSubData(a.ARRAY_BUFFER,0,this.Rd);a.bindBuffer(a.ARRAY_BUFFER,f);a.vertexAttribPointer(b.sc,f.ta,a.FLOAT,!1,0,0);a.bufferSubData(a.ARRAY_BUFFER,0,this.je);a.bindBuffer(a.ARRAY_BUFFER,h);a.vertexAttribPointer(b.og,h.ta,a.FLOAT,!1,0,0);a.bufferSubData(a.ARRAY_BUFFER,
0,this.Dd);a.uniformMatrix4fv(b.ik,a.kl,this.Oc);for(b=0;b<this.J;b++)c=this.R[b],a.activeTexture(a.TEXTURE0+b),a.bindTexture(a.TEXTURE_2D,c),this.ia(a,c.Fe);a.drawArrays(a.TRIANGLES,0,this.Xa*g.yc);this.P++}};e.Kd=function(a,b){0<this.Jc&&this.Tb(a);this.Ga&&console.log("Draw["+this.na+":"+this.P+"] : Cover");var c=this.X,d=this.ke,f=this.ie;a.clear(a.COLOR_BUFFER_BIT);a.useProgram(c);a.bindBuffer(a.ARRAY_BUFFER,d);a.vertexAttribPointer(c.tc,d.ta,a.FLOAT,!1,0,0);a.bufferSubData(a.ARRAY_BUFFER,0,
g.jh);a.bindBuffer(a.ARRAY_BUFFER,f);a.vertexAttribPointer(c.sc,f.ta,a.FLOAT,!1,0,0);a.bufferSubData(a.ARRAY_BUFFER,0,b?g.ih:g.hh);a.uniform1i(c.rd,0);a.uniform1f(c.Wg,b?0:1);a.drawArrays(a.TRIANGLES,0,g.yc)};createjs.Bd=createjs.C(g,"Stage")})();
(function(){function g(a){this.Kb();"string"==typeof a?(this.image=document.createElement("img"),this.image.src=a):this.image=a;this.ma=null;this.Ea=createjs.W.Xh}var e=createjs.extend(g,createjs.W);e.nc=g;e.isVisible=function(){var a=this.image;a=this.i||a&&(a.naturalWidth||a.getContext||2<=a.readyState);return!!(this.visible&&0<this.alpha&&0!=this.D&&0!=this.F&&a)};e.v=function(a,b){if(this.fb(a,b))return!0;var c=this.image,d=this.ma;if(c.Dg&&(c=c.Dg()),!c)return!0;if(d){var f=d.x,h=d.y,k=f+d.width;
d=h+d.height;var l=0,m=0,q=c.width,r=c.height;0>f&&(l-=f,f=0);k>q&&(k=q);0>h&&(m-=h,h=0);d>r&&(d=r);a.drawImage(c,f,h,k-f,d-h,l,m,k-f,d-h)}else a.drawImage(c,0,0);return!0};e.M=function(){var a=this.vc();if(a)return a;a=this.image;var b=this.ma||a;return a&&(a.naturalWidth||a.getContext||2<=a.readyState)?this.yb.H(0,0,b.width,b.height):null};e.clone=function(a){var b=this.image;b&&a&&(b=b.cloneNode());a=new g(b);return this.ma&&(a.ma=this.ma.clone()),this.ja(a),a};e.toString=function(){return"[Bitmap (name="+
this.name+")]"};createjs.Vk=createjs.C(g,"DisplayObject")})();
(function(){function g(a,b){this.Kb();this.currentFrame=0;this.ad=null;this.paused=!0;this.m=a;this.framerate=this.Fb=0;this.Y=this.hb=null;this.hc=!1;this.Ea=createjs.W.Zh;null!=b&&this.dd(b)}var e=createjs.extend(g,createjs.W);e.nc=g;e.isVisible=function(){var a=this.i||this.m.complete;return!!(this.visible&&0<this.alpha&&0!=this.D&&0!=this.F&&a)};e.v=function(a,b){if(this.fb(a,b))return!0;this.cc();var c=this.m.Gb(0|this.Y);if(!c)return!1;var d=c.rect;return d.width&&d.height&&a.drawImage(c.image,
d.x,d.y,d.width,d.height,-c.N,-c.O,d.width,d.height),!0};e.play=function(){this.paused=!1};e.stop=function(){this.paused=!0};e.dd=function(a){this.paused=!1;this.hc=!0;this.pb(a)};e.$a=function(a){this.paused=!0;this.pb(a)};e.advance=function(a){var b=this.framerate||this.m.framerate;this.cc(b&&null!=a?a/(1E3/b):1)};e.M=function(){return this.vc()||this.m.Vj(this.currentFrame,this.yb)};e.clone=function(){return this.ja(new g(this.m))};e.toString=function(){return"[Sprite (name="+this.name+")]"};e.ja=
function(a){return this.qh(a),a.currentFrame=this.currentFrame,a.ad=this.ad,a.paused=this.paused,a.Fb=this.Fb,a.framerate=this.framerate,a.hb=this.hb,a.Y=this.Y,a.hc=this.hc,a};e.fa=function(a){this.paused||(this.hc||this.advance(a&&a.wg),this.hc=!1);this.cf(a)};e.cc=function(a){a=a||0;var b,c=this.hb,d=this.paused,f=this.Y;if(c){var h=c.speed||1,k=this.Fb;if(b=c.frames.length,k+a*h>=b){var l=c.next;if(this.yf(c,f,d,l,b-1))return;if(l)return this.pb(l,a-(b-k)/h);this.paused=!0;k=c.frames.length-1}else k+=
a*h;this.Fb=k;this.Y=c.frames[0|k]}else if(f=this.Y+=a,b=this.m.Xj(),f>=b&&0<b&&!this.yf(c,f,d,b-1)&&(this.Y-=b)>=b)return this.cc();f=0|this.Y;this.currentFrame!=f&&(this.currentFrame=f,this.dispatchEvent("change"))};e.yf=function(a,b,c,d,f){var h=a?a.name:null;if(this.sa("animationend")){var k=new createjs.Event("animationend");k.name=h;k.next=d;this.dispatchEvent(k)}a=this.hb!=a||this.Y!=b;return a||c||!this.paused||(this.Fb=f,a=!0),a};e.pb=function(a,b){if(this.Fb=0,isNaN(a)){var c=this.m.ue(a);
c&&(this.hb=c,this.ad=a,this.cc(b))}else this.ad=this.hb=null,this.Y=a,this.cc()};createjs.Kh=createjs.C(g,"DisplayObject")})();
(function(){function g(a){this.Kb();this.ba=a?a:new createjs.vh}var e=createjs.extend(g,createjs.W);e.isVisible=function(){var a=this.i||this.ba&&!this.ba.gd();return!!(this.visible&&0<this.alpha&&0!=this.D&&0!=this.F&&a)};e.v=function(a,b){return this.fb(a,b)?!0:(this.ba.v(a,this),!0)};e.clone=function(a){a=a&&this.ba?this.ba.clone():this.ba;return this.ja(new g(a))};e.toString=function(){return"[Shape (name="+this.name+")]"};createjs.Bl=createjs.C(g,"DisplayObject")})();
(function(){function g(b,c,d){this.Kb();this.text=b;this.font=c;this.color=d;this.textAlign="left";this.textBaseline="top";this.maxWidth=null;this.lineHeight=this.outline=0;this.lineWidth=null}var e=createjs.extend(g,createjs.W),a=createjs.L?createjs.L():document.createElement("canvas");a.getContext&&(g.me=a.getContext("2d"),a.width=a.height=1);g.wh={start:0,left:0,sm:-.5,end:-1,right:-1};g.mf={top:0,Rm:-.01,$m:-.4,km:-.8,Sm:-.85,bottom:-1};e.isVisible=function(){var b=this.i||null!=this.text&&""!==
this.text;return!!(this.visible&&0<this.alpha&&0!=this.D&&0!=this.F&&b)};e.v=function(b,c){if(this.fb(b,c))return!0;var d=this.color||"#000";return this.outline?(b.strokeStyle=d,b.lineWidth=1*this.outline):b.fillStyle=d,this.Gc(this.ae(b)),!0};e.Mm=function(){return this.Lf(this.text)};e.ye=function(){return 1.2*this.Lf("M")};e.Lm=function(){return this.Gc(null,{}).height};e.M=function(){var b=this.vc();if(b)return b;if(null==this.text||""===this.text)return null;b=this.Gc(null,{});var c=this.maxWidth&&
this.maxWidth<b.width?this.maxWidth:b.width,d=c*g.wh[this.textAlign||"left"],f=(this.lineHeight||this.ye())*g.mf[this.textBaseline||"top"];return this.yb.H(d,f,c,b.height)};e.Nm=function(){var b={lines:[]};return b.lineHeight=this.lineHeight||this.ye(),b.Pn=b.lineHeight*g.mf[this.textBaseline||"top"],this.Gc(null,b,b.lines)};e.clone=function(){return this.ja(new g(this.text,this.font,this.color))};e.toString=function(){return"[Text (text="+(20<this.text.length?this.text.substr(0,17)+"...":this.text)+
")]"};e.ja=function(b){return this.qh(b),b.textAlign=this.textAlign,b.textBaseline=this.textBaseline,b.maxWidth=this.maxWidth,b.outline=this.outline,b.lineHeight=this.lineHeight,b.lineWidth=this.lineWidth,b};e.ae=function(b){return b.font=this.font||"10px sans-serif",b.textAlign=this.textAlign||"left",b.textBaseline=this.textBaseline||"top",b.lineJoin="miter",b.miterLimit=2.5,b};e.Gc=function(b,c,d){var f=!!b;f||(b=g.me,b.save(),this.ae(b));for(var h=this.lineHeight||this.ye(),k=0,l=0,m=String(this.text).split(/(?:\r\n|\r|\n)/),
q=0,r=m.length;r>q;q++){var n=m[q],p=null;if(null!=this.lineWidth&&(p=b.measureText(n).width)>this.lineWidth){var t=n.split(/(\s)/);n=t[0];p=b.measureText(n).width;for(var x=1,A=t.length;A>x;x+=2){var y=b.measureText(t[x]+t[x+1]).width;p+y>this.lineWidth?(f&&this.Af(b,n,l*h),d&&d.push(n),p>k&&(k=p),n=t[x+1],p=b.measureText(n).width,l++):(n+=t[x]+t[x+1],p+=y)}}f&&this.Af(b,n,l*h);d&&d.push(n);c&&null==p&&(p=b.measureText(n).width);p>k&&(k=p);l++}return c&&(c.width=k,c.height=l*h),f||b.restore(),c};
e.Af=function(b,c,d){this.outline?b.strokeText(c,0,d,this.maxWidth||65535):b.fillText(c,0,d,this.maxWidth||65535)};e.Lf=function(b){var c=g.me;c.save();b=this.ae(c).measureText(b).width;return c.restore(),b};createjs.Text=createjs.C(g,"DisplayObject")})();
(function(){function g(a,b){this.bf();this.text=a||"";this.m=b;this.sd=this.letterSpacing=this.lineHeight=0;this.Nc={text:0,m:0,lineHeight:0,letterSpacing:0,sd:0};this.Fc=this.Wd=null}var e=createjs.extend(g,createjs.uc);g.Hg=100;g.$i=[];e.v=function(a,b){this.fb(a,b)||(this.Db(),this.oh(a,b))};e.M=function(){return this.lg(),this.fl()};e.isVisible=function(){var a=this.i||this.m&&this.m.complete&&this.text;return!!(this.visible&&0<this.alpha&&0!==this.D&&0!==this.F&&a)};e.clone=function(){return this.ja(new g(this.text,
this.m))};e.ng=e.ne=e.removeChild=e.Og=e.Ng=function(){};e.Db=function(){this.lg()};e.ja=function(a){return this.cl(a),a.lineHeight=this.lineHeight,a.letterSpacing=this.letterSpacing,a.sd=this.sd,a};e.Jf=function(a,b){var c,d=b.ue(a);return d||(a!=(c=a.toUpperCase())||a!=(c=a.toLowerCase())||(c=null),c&&(d=b.ue(c))),d&&d.frames[0]};e.za=function(a,b){var c=this.Jf(a,b);return null==c?c:b.Gb(c)};e.ri=function(a){return(a=this.za("1",a)||this.za("T",a)||this.za("L",a)||a.Gb(0))?a.rect.height:1};e.ui=
function(a){return(a=this.za("1",a)||this.za("l",a)||this.za("e",a)||this.za("a",a)||a.Gb(0))?a.rect.width:1};e.lg=function(){var a,b=0,c=0,d=this.Nc,f=!1,h=this.sd,k=this.lineHeight,l=this.m,m=g.$i,q=this.children,r=0,n=q.length,p;for(p in d)d[p]!=this[p]&&(d[p]=this[p],f=!0);if(f){(d=!!this.za(" ",l))||h||(h=this.ui(l));k||(k=this.ri(l));f=0;for(p=this.text.length;p>f;f++){var t=this.text.charAt(f);" "!=t||d?"\n"!=t&&"\r"!=t?(t=this.Jf(t,l),null!=t&&(n>r?a=q[r]:(q.push(a=m.length?m.pop():new createjs.Kh),
a.parent=this,n++),a.m=l,a.$a(t),a.x=b,a.y=c,r++,b+=a.M().width+this.letterSpacing)):("\r"==t&&"\n"==this.text.charAt(f+1)&&f++,b=0,c+=k):b+=h}for(;n>r;)m.push(a=q.pop()),a.parent=null,n--;m.length>g.Hg&&(m.length=g.Hg)}};createjs.Wk=createjs.C(g,"Container")})();
(function(){function g(b){this.bf();!g.De&&g.fd();var c,d,f,h;b instanceof String||1<arguments.length?(c=b,d=arguments[1],f=arguments[2],h=arguments[3],null==f&&(f=-1),b=null):b&&(c=b.mode,d=b.Sg,f=b.loop,h=b.labels);b||(b={labels:h});this.mode=c||g.Nb;this.Sg=d||0;this.loop=!0===f?-1:f||0;this.currentFrame=0;this.paused=b.paused||!1;this.oj=this.kc=!0;this.lc=this.lc||b.lc;this.framerate=null;b.Nn=b.paused=!0;this.timeline=new createjs.Jl(b);this.fg=0;this.fc=-1;this.tf=this.Ui.bind(this);this.Uc=
0;this.tb={}}function e(){throw"MovieClipPlugin cannot be instantiated.";}var a=createjs.extend(g,createjs.uc);g.Nb="independent";g.Hh="single";g.De=!1;g.fd=function(){g.De||(e.install(),g.De=!0)};a.Kf=function(){return this.timeline.Wj()};a.Wj=createjs.ka(a.Kf,"MovieClip.getLabels");a.Gf=function(){return this.timeline.Gj};a.Gm=createjs.ka(a.Gf,"MovieClip.getCurrentLabel");a.Hf=function(){return this.timeline.duration};a.Im=createjs.ka(a.Hf,"MovieClip.getDuration");try{Object.defineProperties(a,
{labels:{get:a.Kf},Gj:{get:a.Gf},duration:{get:a.Hf}})}catch(b){}a.nc=g;a.isVisible=function(){return!!(this.visible&&0<this.alpha&&0!=this.D&&0!=this.F)};a.v=function(b,c){return this.fb(b,c)?!0:(this.Db(),this.oh(b,c),!0)};a.play=function(){this.paused=!1};a.stop=function(){this.paused=!0};a.dd=function(b){this.paused=!1;this.pb(b)};a.$a=function(b){this.paused=!0;this.pb(b)};a.advance=function(b){var c=g.Nb;if(this.mode===c){for(var d=this,f=d.framerate;(d=d.parent)&&null===f;)d.mode===c&&(f=d.li);
if(this.li=f,!this.paused)for(b=null!==f&&-1!==f&&null!==b?b/(1E3/f)+this.Uc:1,c=0|b,this.Uc=b-c;c--;)this.he(this.fc+1,!1)}};a.clone=function(){throw"MovieClip cannot be cloned.";};a.toString=function(){return"[MovieClip (name="+this.name+")]"};a.Db=function(){-1!==this.fc&&this.mode===g.Nb||this.he(-1)};a.fa=function(b){this.advance(b&&b.wg);this.el(b)};a.pb=function(b){b=this.timeline.resolve(b);null!=b&&(this.Uc=0,this.he(b,!0))};a.Sa=function(){this.fc=-1;this.Uc=this.currentFrame=0;this.paused=
!1};a.he=function(b,c){var d=this.mode!==g.Nb,f=this.timeline;d&&(b=this.Sg+(this.mode===g.Hh?0:this.fg));0>b&&(b=0);(this.fc!==b||d)&&(this.fc=b,f.loop=this.loop,f.setPosition(b,d||!this.kc,c,this.tf))};a.dm=function(){var b=this.timeline,c=b.vk;b.setPosition(0,!0,!0,this.tf);b.vk=c};a.Ui=function(){var b=this.timeline;this.currentFrame=b.position;for(var c in this.tb)this.tb[c]=1;c=b.Jn;b=0;for(var d=c.length;d>b;b++){var f=c[b],h=f.target;h===this||f.passive||(f=f.gm,h instanceof createjs.W?this.nf(h,
f):this.Xi(h.state,f))}c=this.children;for(b=c.length-1;0<=b;b--)d=c[b].id,1===this.tb[d]&&(this.Og(b),delete this.tb[d])};a.Xi=function(b,c){if(b)for(var d=b.length-1;0<=d;d--){var f=b[d],h=f.t;f=f.p;for(var k in f)h[k]=f[k];this.nf(h,c)}};a.nf=function(b,c){b.cm||(this.ne(b,0),b instanceof g&&(b.fg=c,b.mode===g.Nb&&b.oj&&!this.tb[b.id]&&b.Sa()),this.tb[b.id]=2)};a.nb=function(b,c){var d=this.vc();return d||this.lc&&(d=this.yb.ga(this.lc[this.currentFrame])),d?this.ge(d,b,c):this.dl(b,c)};createjs.sl=
createjs.C(g,"Container");e.priority=100;e.install=function(){createjs.Kl.$l(e)};e.fd=function(){};e.step=function(){}})();(function(){function g(){throw"SpriteSheetUtils cannot be instantiated";}var e=createjs.L?createjs.L():document.createElement("canvas");e.getContext&&(g.me=e.getContext("2d"),e.width=e.height=1);createjs.Dl=g})();
(function(){function g(a){this.ef();this.maxHeight=this.maxWidth=2048;this.m=null;this.padding=this.scale=1;this.We=.3;this.progress=-1;this.framerate=a||0;this.u=[];this.ib={};this.K=null;this.Hc=0;this.fe=null;this.ce=1}var e=createjs.extend(g,createjs.wc);g.df="frame dimensions exceed max spritesheet dimensions";g.Lb="a build is already running";e.hj=function(a,b,c,d,f){if(this.K)throw g.Lb;b=b||a.wj||a.hk;!b&&a.M&&(b=a.M());b&&(c=c||1,this.u.push({source:a,ma:b,scale:c,Bg:d,data:f,index:this.u.length,
height:b.height*c}))};e.gj=function(a,b){if(this.K)throw g.Lb;this.ib[a]={frames:b,next:!0,speed:void 0}};e.jm=function(a,b,c,d,f,h){if(this.K)throw g.Lb;var k=a.lc,l=b||a.wj||a.hk;if(!l&&a.M&&(l=a.M()),l||k){var m,q;b=this.u.length;var r=a.timeline.duration;for(m=0;r>m;m++)this.hj(a,k&&k[m]?k[m]:l,c,this.Zi,{Be:m,f:d,d:f});m=a.timeline.am;c=[];for(q in m)c.push({index:m[q],label:q});if(c.length)for(c.sort(function(p,t){return p.index-t.index}),m=0,q=c.length;q>m;m++){d=c[m].label;f=b+c[m].index;
k=b+(m==q-1?r:c[m+1].index);l=[];for(var n=f;k>n;n++)l.push(n);h&&!(d=h(d,a,f,k))||this.gj(d,l)}}};e.pm=function(){if(this.K)throw g.Lb;for(this.eg();this.zf(););return this.Bf(),this.m};e.qm=function(a){if(this.K)throw g.Lb;this.We=a;this.eg();var b=this;this.fe=setTimeout(function(){b.ag()},50-50*Math.max(.01,Math.min(.99,this.We||.3)))};e.Gn=function(){clearTimeout(this.fe);this.K=null};e.clone=function(){throw"SpriteSheetBuilder cannot be cloned.";};e.toString=function(){return"[SpriteSheetBuilder]"};
e.eg=function(){var a=this.padding||0;this.progress=0;this.m=null;this.Hc=0;this.ce=this.scale;var b=[];this.K={images:[],frames:b,framerate:this.framerate,pg:this.ib};var c=this.u.slice();if(c.sort(function(m,q){return m.height<=q.height?-1:1}),c[c.length-1].height+2*a>this.maxHeight)throw g.df;for(var d=0,f=0,h=0;c.length;){var k=this.ji(c,d,h,b,a);if(k.w>f&&(f=k.w),d+=k.la,!k.la||!c.length){var l=createjs.L?createjs.L():document.createElement("canvas");l.width=this.Mf(f,this.maxWidth);l.height=
this.Mf(d,this.maxHeight);this.K.images[h]=l;k.la||(f=d=0,h++)}}};e.Zi=function(a,b){var c=a.kc;a.kc=!1;a.$a(b.Be);a.kc=c;b.f&&b.f(a,b.d,b.Be)};e.Mf=function(a,b){for(var c=4;Math.pow(2,++c)<a;);return Math.min(b,Math.pow(2,c))};e.ji=function(a,b,c,d,f){var h=this.maxWidth,k=this.maxHeight;b+=f;k-=b;for(var l=f,m=0,q=a.length-1;0<=q;q--){var r=a[q],n=this.ce*r.scale,p=r.ma,t=r.source,x=Math.floor(n*p.x-f),A=Math.floor(n*p.y-f),y=Math.ceil(n*p.height+2*f);p=Math.ceil(n*p.width+2*f);if(p>h)throw g.df;
y>k||l+p>h||(r.ak=c,r.rect=new createjs.wa(l,b,p,y),m=m||y,a.splice(q,1),d[r.index]=[l,b,p,y,c,Math.round(-x+n*t.N-f),Math.round(-A+n*t.O-f)],l+=p)}return{w:l,la:m}};e.Bf=function(){this.m=new createjs.Lh(this.K);this.K=null;this.progress=1;this.dispatchEvent("complete")};e.ag=function(){for(var a=50*Math.max(.01,Math.min(.99,this.We||.3)),b=(new Date).getTime()+a,c=!1;b>(new Date).getTime();)if(!this.zf()){c=!0;break}if(c)this.Bf();else{var d=this;this.fe=setTimeout(function(){d.ag()},50-a)}a=this.progress=
this.Hc/this.u.length;this.sa("progress")&&(b=new createjs.Event("progress"),b.progress=a,this.dispatchEvent(b))};e.zf=function(){var a=this.u[this.Hc],b=a.scale*this.ce,c=a.rect,d=a.ma,f=this.K.images[a.ak].getContext("2d");return a.Bg&&a.Bg(a.source,a.data),f.save(),f.beginPath(),f.rect(c.x,c.y,c.width,c.height),f.clip(),f.translate(Math.ceil(c.x-d.x*b),Math.ceil(c.y-d.y*b)),f.scale(b,b),a.source.v(f),f.restore(),++this.Hc<this.u.length};createjs.Cl=createjs.C(g,"EventDispatcher")})();
(function(){function g(a){this.Kb();"string"==typeof a&&(a=document.getElementById(a));this.ld=!1;var b=a.style;b.position="absolute";b.transformOrigin=b.WebkitTransformOrigin=b.fn=b.MozTransformOrigin=b.wl="0% 0%";this.Gg=a;this.Fc=this.Wd=this.Nc=null}var e=createjs.extend(g,createjs.W);e.isVisible=function(){return null!=this.Gg};e.v=function(){return!0};e.cache=function(){};e.Vg=function(){};e.Lk=function(){};e.Fg=function(){};e.kd=function(){};e.cd=function(){};e.dk=function(){};e.clone=function(){throw"DOMElement cannot be cloned.";
};e.toString=function(){return"[DOMElement (name="+this.name+")]"};e.fa=function(a){var b=this.Jb;b&&b!==this.Wd&&(this.Fc&&b.Ke("drawend",this.Fc),this.Fc=b.Ne("drawend",this.xi,this),this.Wd=b);this.cf(a)};e.xi=function(){var a=this.Gg;if(a){a=a.style;var b=this.Cg(this.Z),c=b.l,d=b.visible?"visible":"hidden";if(d!=a.visibility&&(a.visibility=d),b.visible){var f=(d=this.Nc)&&d.l;f&&f.Qj(c)||(f="matrix("+(1E4*c.a|0)/1E4+","+(1E4*c.b|0)/1E4+","+(1E4*c.c|0)/1E4+","+(1E4*c.d|0)/1E4+","+(c.h+.5|0),a.transform=
a.WebkitTransform=a.vl=a.msTransform=f+","+(c.g+.5|0)+")",a.MozTransform=f+"px,"+(c.g+.5|0)+"px)",d||(d=this.Nc=new createjs.vd(!0,null)),d.l.ga(c));d.alpha!=b.alpha&&(a.opacity=""+(1E4*b.alpha|0)/1E4,d.alpha=b.alpha)}}};createjs.hl=createjs.C(g,"DisplayObject")})();
(function(){function g(){this.Xg=!1;this.gb=this.Ph=this.ac=null}var e=g.prototype;e.M=function(a){return a};e.va=function(){};e.qg=function(a,b,c,d,f){var h,k;var l=l||a;null==h&&(h=b);null==k&&(k=c);try{var m=a.getImageData(b,c,d,f)}catch(q){return}this.jb(m)&&l.putImageData(m,h,k)};e.toString=function(){return"[Filter]"};e.clone=function(){return new g};e.jb=function(){return!0};createjs.Mb=g})();
(function(){function g(){this.y=this.x=this.height=this.width=void 0;this.scale=1;this.Id=this.Vb=this.Ub=this.ra=this.Me=this.Le=0;this.Hd=null;this.o=this.s=0}var e=g.prototype;g.Uj=function(a){var b;b||(b=new createjs.wa);var c=(a=a.filters)&&a.length;if(0>=!!c)return b;for(var d=0;c>d;d++){var f=a[d];f&&f.M&&(f=f.M())&&(0==d?b.H(f.x,f.y,f.width,f.height):b.extend(f.x,f.y,f.width,f.height))}return b};e.toString=function(){return"[BitmapCache]"};e.define=function(a,b,c,d,f,h,k){if(!a)throw"No symbol to cache";
this.Ra=k;this.target=a;this.width=1<=d?d:1;this.height=1<=f?f:1;this.x=b||0;this.y=c||0;this.scale=h||1;this.update()};e.update=function(a){if(!this.target)throw"define() must be called before update()";var b=g.Uj(this.target),c=this.target.i;this.s=Math.ceil(this.width*this.scale)+b.width;this.o=Math.ceil(this.height*this.scale)+b.height;c&&this.s==c.width&&this.o==c.height||this.bj();this.Ub=b.x;this.Vb=b.y;this.Le=this.x*this.scale+this.Ub;this.Me=this.y*this.scale+this.Vb;this.hi(a);this.ra=
this.ra?this.ra+1:1};e.release=function(){if(this.$)this.$.Hb||(this.Ac&&(this.Ac=void 0),this.xa&&this.$.sb(this.xa),this.Ja&&this.$.sb(this.Ja),this.target&&this.target.i&&this.$.sb(this.target.i)),this.$=!1;else{var a=this.target.Jb;a instanceof createjs.Bd&&a.Se(this.target.i)}this.target=this.target.i=null;this.ra=this.Id=this.Hd=void 0;this.width=this.height=this.x=this.y=this.Le=this.Me=0;this.scale=1};e.Tj=function(){var a=this.target&&this.target.i;return a?(this.ra!=this.Id&&(this.Id=this.ra,
this.Hd=a.toDataURL?a.toDataURL():null),this.Hd):null};e.v=function(a){return this.target?(a.drawImage(this.target.i,this.x+this.Ub/this.scale,this.y+this.Vb/this.scale,this.s/this.scale,this.o/this.scale),!0):!1};e.bj=function(){if(this.Ra&&this.Ra.rc){if(!this.$)if("stage"===this.Ra.rc){if(!this.target.Jb||!this.target.Jb.ck)throw"Cannot use 'stage' for cache because the object's parent stage is "+(this.target.Jb?"non WebGL.":"not set, please addChild to the correct stage.");this.target.i=!0;this.$=
this.target.Jb}else{if("new"===this.Ra.rc)this.target.i=document.createElement("canvas"),this.$=new createjs.Bd(this.target.i,{antialias:!0,Kk:!0,qe:-1});else{if(!(this.Ra.rc instanceof createjs.Bd))throw"Invalid option provided to useGL, expected ['stage', 'new', StageGL, undefined], got "+this.Ra.rc;this.target.i=!0;this.$=this.Ra.rc}this.$.Hb=!0}b=this.target.i;var a=this.$;a.Hb&&(b.width=this.s,b.height=this.o,a.eb(this.s,this.o));this.target.filters?(a.Za(this.target,this.s,this.o),a.Za(this.target,
this.s,this.o)):a.Hb||a.Za(this.target,this.s,this.o)}else{var b=this.target.i;b||(b=this.target.i=createjs.L?createjs.L():document.createElement("canvas"));b.width=this.s;b.height=this.o}};e.hi=function(a){var b=this.target.i,c=this.target,d=this.$;d?(d.yj(c,c.filters,this),b=this.target.i,b.width=this.s,b.height=this.o):(d=b.getContext("2d"),a||d.clearRect(0,0,this.s+1,this.o+1),d.save(),d.globalCompositeOperation=a,d.setTransform(this.scale,0,0,this.scale,-this.Ub,-this.Vb),d.translate(-this.x,
-this.y),c.v(d,!0),d.restore(),c.filters&&c.filters.length&&this.ai(d));b.Sd=!0};e.ai=function(a){var b,c=this.target.filters,d=this.s,f=this.o,h=0,k=c[h];do k.Xg?(b&&(a.putImageData(b,0,0),b=null),k.qg(a,0,0,d,f)):(b||(b=a.getImageData(0,0,d,f)),k.jb(b)),k=null!==k.ac?k.ac:c[++h];while(k);b&&a.putImageData(b,0,0)};createjs.eh=g})();
(function(){function g(a,b,c){this.xc();this.Ma=a;this.Ed=[];this.Uf=null;this.Na=b;this.Fd=[];this.Vf=null;this.Ba;this.Wf=null;this.uh="uniform float xWeight[{{blurX}}];uniform float yWeight[{{blurY}}];uniform vec2 textureOffset;void main(void) {vec4 color = vec4(0.0);float xAdj = ({{blurX}}.0-1.0)/2.0;float yAdj = ({{blurY}}.0-1.0)/2.0;vec2 sampleOffset;for(int i=0; i<{{blurX}}; i++) {for(int j=0; j<{{blurY}}; j++) {sampleOffset = vRenderCoord + (textureOffset * vec2(float(i)-xAdj, float(j)-yAdj));color += texture2D(uSampler, sampleOffset) * (xWeight[i] * yWeight[j]);}}gl_FragColor = color.rgba;}";(isNaN(c)||
1>c)&&(c=1);this.Pg(0|c)}var e=createjs.extend(g,createjs.Mb);e.Rj=function(){return this.Ma};e.Sj=function(){return this.Na};e.yk=function(a){(isNaN(a)||0>a)&&(a=0);this.Ma=a};e.zk=function(a){(isNaN(a)||0>a)&&(a=0);this.Na=a};e.Zj=function(){return this.Ba};e.Pg=function(a){(isNaN(a)||0>a)&&(a=0);this.Ba=0|a};e.ti=function(){var a=this.Uf!==this.Ma,b=this.Vf!==this.Na,c=this.Wf!==this.Ba;return a||b||c?((a||c)&&(this.Ed=this.Of(this.Ma*this.Ba)),(b||c)&&(this.Fd=this.Of(this.Na*this.Ba)),this.aj(),
this.Uf=this.Ma,this.Vf=this.Na,void(this.Wf=this.Ba)):this.ei};e.Wi=function(){this.ei};try{Object.defineProperties(e,{ug:{get:e.Rj,set:e.yk},vg:{get:e.Sj,set:e.zk},quality:{get:e.Zj,set:e.Pg},Gd:{get:e.ti,set:e.Wi}})}catch(a){console.log(a)}e.Of=function(a){if(1>=a)return[1];var b=[];a=Math.ceil(2*a);a=(a+(a%2?0:1))/2|0;for(var c=-a;a>=c;c++)b.push(1/Math.sqrt(2*Math.PI)*Math.pow(Math.E,-(Math.pow(c/a*4.2,2)/4)));var d=b.reduce(function(f,h){return f+h});return b.map(function(f){return f/d})};e.aj=
function(){if(void 0!==this.Ma&&void 0!==this.Na){var a=this.uh;a=a.replace(/\{\{blurX\}\}/g,this.Ed.length.toFixed(0));this.gb=a=a.replace(/\{\{blurY\}\}/g,this.Fd.length.toFixed(0))}};e.va=function(a,b,c){a.uniform1fv(a.getUniformLocation(c,"xWeight"),this.Ed);a.uniform1fv(a.getUniformLocation(c,"yWeight"),this.Fd);a.uniform2f(a.getUniformLocation(c,"textureOffset"),2/(b.Wa*this.Ba),2/(b.Va*this.Ba))};g.ff=[1,171,205,293,57,373,79,137,241,27,391,357,41,19,283,265,497,469,443,421,25,191,365,349,
335,161,155,149,9,278,269,261,505,245,475,231,449,437,213,415,405,395,193,377,369,361,353,345,169,331,325,319,313,307,301,37,145,285,281,69,271,267,263,259,509,501,493,243,479,118,465,459,113,446,55,435,429,423,209,413,51,403,199,393,97,3,379,375,371,367,363,359,355,351,347,43,85,337,333,165,327,323,5,317,157,311,77,305,303,75,297,294,73,289,287,71,141,279,277,275,68,135,67,133,33,262,260,129,511,507,503,499,495,491,61,121,481,477,237,235,467,232,115,457,227,451,7,445,221,439,218,433,215,427,425,
211,419,417,207,411,409,203,202,401,399,396,197,49,389,387,385,383,95,189,47,187,93,185,23,183,91,181,45,179,89,177,11,175,87,173,345,343,341,339,337,21,167,83,331,329,327,163,81,323,321,319,159,79,315,313,39,155,309,307,153,305,303,151,75,299,149,37,295,147,73,291,145,289,287,143,285,71,141,281,35,279,139,69,275,137,273,17,271,135,269,267,133,265,33,263,131,261,130,259,129,257,1];g.kf=[0,9,10,11,9,12,10,11,12,9,13,13,10,9,13,13,14,14,14,14,10,13,14,14,14,13,13,13,9,14,14,14,15,14,15,14,15,15,14,
15,15,15,14,15,15,15,15,15,14,15,15,15,15,15,15,12,14,15,15,13,15,15,15,15,16,16,16,15,16,14,16,16,14,16,13,16,16,16,15,16,13,16,15,16,14,9,16,16,16,16,16,16,16,16,16,13,14,16,16,15,16,16,10,16,15,16,14,16,16,14,16,16,14,16,16,14,15,16,16,16,14,15,14,15,13,16,16,15,17,17,17,17,17,17,14,15,17,17,16,16,17,16,15,17,16,17,11,17,16,17,16,17,16,17,17,16,17,17,16,17,17,16,16,17,17,17,16,14,17,17,17,17,15,16,14,16,15,16,13,16,15,16,14,16,15,16,12,16,15,16,17,17,17,17,17,13,16,15,17,17,17,16,15,17,17,17,16,
15,17,17,14,16,17,17,16,17,17,16,15,17,16,14,17,16,15,17,16,17,17,16,17,15,16,17,14,17,16,15,17,16,17,13,17,16,17,17,16,17,14,17,16,17,16,17,16,17,9];e.M=function(a){var b=0|this.ug,c=0|this.vg;if(0>=b&&0>=c)return a;var d=Math.pow(this.quality,.2);return(a||new createjs.wa).jk(c*d+1,b*d+1,c*d+1,b*d+1)};e.clone=function(){return new g(this.ug,this.vg,this.quality)};e.toString=function(){return"[BlurFilter]"};e.jb=function(a){var b=this.Ma>>1;if(isNaN(b)||0>b)return!1;var c=this.Na>>1;if(isNaN(c)||
0>c||0==b&&0==c)return!1;var d=this.quality;(isNaN(d)||1>d)&&(d=1);d|=0;3<d&&(d=3);1>d&&(d=1);var f=a.data,h,k=0,l,m,q,r,n=b+b+1|0;var p=c+c+1|0;var t=0|a.width;a=0|a.height;var x=t-1|0,A=a-1|0,y=b+1|0,v=c+1|0,z={r:0,b:0,A:0,a:0};var w=z;for(h=1;n>h;h++)w=w.n={r:0,b:0,A:0,a:0};w.n=z;var u=n={r:0,b:0,A:0,a:0};for(h=1;p>h;h++)u=u.n={r:0,b:0,A:0,a:0};u.n=n;for(var E=0|g.ff[b],F=0|g.kf[b],B=0|g.ff[c],L=0|g.kf[c];0<d--;){var K=p=0;var C=E,D=F;for(u=a;-1<--u;){var G=y*(m=f[0|p]);var H=y*(q=f[p+1|0]);var I=
y*(r=f[p+2|0]);var J=y*(l=f[p+3|0]);w=z;for(h=y;-1<--h;)w.r=m,w.A=q,w.b=r,w.a=l,w=w.n;for(h=1;y>h;h++)k=p+((h>x?x:h)<<2)|0,G+=w.r=f[k],H+=w.A=f[k+1],I+=w.b=f[k+2],J+=w.a=f[k+3],w=w.n;h=z;for(w=0;t>w;w++)f[p++]=G*C>>>D,f[p++]=H*C>>>D,f[p++]=I*C>>>D,f[p++]=J*C>>>D,k=K+((k=w+b+1)<x?k:x)<<2,G-=h.r-(h.r=f[k]),H-=h.A-(h.A=f[k+1]),I-=h.b-(h.b=f[k+2]),J-=h.a-(h.a=f[k+3]),h=h.n;K+=t}C=B;D=L;for(w=0;t>w;w++){p=w<<2|0;G=v*(m=f[p])|0;H=v*(q=f[p+1|0])|0;I=v*(r=f[p+2|0])|0;J=v*(l=f[p+3|0])|0;u=n;for(h=0;v>h;h++)u.r=
m,u.A=q,u.b=r,u.a=l,u=u.n;l=t;for(h=1;c>=h;h++)p=l+w<<2,G+=u.r=f[p],H+=u.A=f[p+1],I+=u.b=f[p+2],J+=u.a=f[p+3],u=u.n,A>h&&(l+=t);if(p=w,h=n,0<d)for(u=0;a>u;u++)k=p<<2,f[k+3]=l=J*C>>>D,0<l?(f[k]=G*C>>>D,f[k+1]=H*C>>>D,f[k+2]=I*C>>>D):f[k]=f[k+1]=f[k+2]=0,k=w+((k=u+v)<A?k:A)*t<<2,G-=h.r-(h.r=f[k]),H-=h.A-(h.A=f[k+1]),I-=h.b-(h.b=f[k+2]),J-=h.a-(h.a=f[k+3]),h=h.n,p+=t;else for(u=0;a>u;u++)k=p<<2,f[k+3]=l=J*C>>>D,0<l?(l=255/l,f[k]=(G*C>>>D)*l,f[k+1]=(H*C>>>D)*l,f[k+2]=(I*C>>>D)*l):f[k]=f[k+1]=f[k+2]=0,
k=w+((k=u+v)<A?k:A)*t<<2,G-=h.r-(h.r=f[k]),H-=h.A-(h.A=f[k+1]),I-=h.b-(h.b=f[k+2]),J-=h.a-(h.a=f[k+3]),h=h.n,p+=t}}return!0};createjs.Xk=createjs.C(g,"Filter")})();
(function(){function g(a){this.xc();this.Eb=a;this.vb=this.ub=this.Cc=null;this.gb="uniform sampler2D uAlphaSampler;void main(void) {vec4 color = texture2D(uSampler, vRenderCoord);vec4 alphaMap = texture2D(uAlphaSampler, vTextureCoord);gl_FragColor = vec4(color.rgb, color.a * (alphaMap.r * ceil(alphaMap.a)));}"}var e=createjs.extend(g,createjs.Mb);e.va=function(a,b,c){this.vb||(this.vb=a.createTexture());a.activeTexture(a.TEXTURE1);a.bindTexture(a.TEXTURE_2D,this.vb);b.ia(a);a.texImage2D(a.TEXTURE_2D,
0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,this.Eb);a.uniform1i(a.getUniformLocation(c,"uAlphaSampler"),1)};e.clone=function(){var a=new g(this.Eb);return a.Cc=this.Cc,a.ub=this.ub,a};e.toString=function(){return"[AlphaMapFilter]"};e.jb=function(a){if(!this.Eb)return!0;if(!this.Si())return!1;a=a.data;for(var b=this.ub,c=0,d=a.length;d>c;c+=4)a[c+3]=b[c]||0;return!0};e.Si=function(){if(!this.Eb)return!1;if(this.Eb==this.Cc&&this.ub)return!0;this.ub=null;var a,b=this.Cc=this.Eb,c=b;b instanceof HTMLCanvasElement?
a=c.getContext("2d"):(c=createjs.L?createjs.L():document.createElement("canvas"),c.width=b.width,c.height=b.height,a=c.getContext("2d"),a.drawImage(b,0,0));try{var d=a.getImageData(0,0,b.width,b.height)}catch(f){return!1}return this.ub=d.data,!0};createjs.Sk=createjs.C(g,"Filter")})();
(function(){function g(a){this.xc();this.ua=a;this.Xg=!0;this.gb="uniform sampler2D uAlphaSampler;void main(void) {vec4 color = texture2D(uSampler, vRenderCoord);vec4 alphaMap = texture2D(uAlphaSampler, vTextureCoord);gl_FragColor = vec4(color.rgb, color.a * alphaMap.a);}"}var e=createjs.extend(g,createjs.Mb);e.va=function(a,b,c){this.vb||(this.vb=a.createTexture());a.activeTexture(a.TEXTURE1);a.bindTexture(a.TEXTURE_2D,this.vb);b.ia(a);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,this.ua);
a.uniform1i(a.getUniformLocation(c,"uAlphaSampler"),1)};e.qg=function(a,b,c){var d,f,h;this.ua&&(d=d||a,null==f&&(f=b),null==h&&(h=c),d.save(),a!=d||(d.globalCompositeOperation="destination-in",d.drawImage(this.ua,f,h),d.restore()))};e.clone=function(){return new g(this.ua)};e.toString=function(){return"[AlphaMaskFilter]"};createjs.Tk=createjs.C(g,"Filter")})();
(function(){function g(a,b,c,d,f,h,k,l){this.xc();this.Qe=null!=a?a:1;this.ze=null!=b?b:1;this.se=null!=c?c:1;this.oe=null!=d?d:1;this.Re=f||0;this.Ae=h||0;this.te=k||0;this.pe=l||0;this.gb="uniform vec4 uColorMultiplier;uniform vec4 uColorOffset;void main(void) {vec4 color = texture2D(uSampler, vRenderCoord);gl_FragColor = (color * uColorMultiplier) + uColorOffset;}"}var e=createjs.extend(g,createjs.Mb);e.va=function(a,b,c){a.uniform4f(a.getUniformLocation(c,"uColorMultiplier"),this.Qe,this.ze,this.se,
this.oe);a.uniform4f(a.getUniformLocation(c,"uColorOffset"),this.Re/255,this.Ae/255,this.te/255,this.pe/255)};e.toString=function(){return"[ColorFilter]"};e.clone=function(){return new g(this.Qe,this.ze,this.se,this.oe,this.Re,this.Ae,this.te,this.pe)};e.jb=function(a){a=a.data;for(var b=a.length,c=0;b>c;c+=4)a[c]=a[c]*this.Qe+this.Re,a[c+1]=a[c+1]*this.ze+this.Ae,a[c+2]=a[c+2]*this.se+this.te,a[c+3]=a[c+3]*this.oe+this.pe;return!0};createjs.$k=createjs.C(g,"Filter")})();
(function(){function g(a,b,c,d){this.Ak(a,b,c,d)}var e=g.prototype;g.ud=[0,.01,.02,.04,.05,.06,.07,.08,.1,.11,.12,.14,.15,.16,.17,.18,.2,.21,.22,.24,.25,.27,.28,.3,.32,.34,.36,.38,.4,.42,.44,.46,.48,.5,.53,.56,.59,.62,.65,.68,.71,.74,.77,.8,.83,.86,.89,.92,.95,.98,1,1.06,1.12,1.18,1.24,1.3,1.36,1.42,1.48,1.54,1.6,1.66,1.72,1.78,1.84,1.9,1.96,2,2.12,2.25,2.37,2.5,2.62,2.75,2.87,3,3.2,3.4,3.6,3.8,4,4.3,4.7,4.9,5,5.5,6,6.5,6.8,7,7.3,7.5,7.8,8,8.4,8.7,9,9.4,9.6,9.8,10];g.wd=[1,0,0,0,0,0,1,0,0,0,0,0,1,
0,0,0,0,0,1,0,0,0,0,0,1];g.Ia=g.wd.length;e.Ak=function(a,b,c,d){this.reset().jj(a,b,c,d)};e.reset=function(){return this.ga(g.wd)};e.jj=function(a,b,c,d){this.lj(d);this.kj(b);this.ij(a);this.mj(c)};e.ij=function(a){0==a||isNaN(a)||(a=this.Ec(a,255),this.bc([1,0,0,0,a,0,1,0,0,a,0,0,1,0,a,0,0,0,1,0,0,0,0,0,1]))};e.kj=function(a){if(0!=a&&!isNaN(a)){a=this.Ec(a,100);var b;0>a?b=127+a/100*127:(b=a%1,b=0==b?g.ud[a]:g.ud[a<<0]*(1-b)+g.ud[(a<<0)+1]*b,b=127*b+127);this.bc([b/127,0,0,0,.5*(127-b),0,b/127,
0,0,.5*(127-b),0,0,b/127,0,.5*(127-b),0,0,0,1,0,0,0,0,0,1])}};e.mj=function(a){0==a||isNaN(a)||(a=this.Ec(a,100),a=1+(0<a?3*a/100:a/100),this.bc([.3086*(1-a)+a,.6094*(1-a),.082*(1-a),0,0,.3086*(1-a),.6094*(1-a)+a,.082*(1-a),0,0,.3086*(1-a),.6094*(1-a),.082*(1-a)+a,0,0,0,0,0,1,0,0,0,0,0,1]))};e.lj=function(a){if(0!=a&&!isNaN(a)){a=this.Ec(a,180)/180*Math.PI;var b=Math.cos(a);a=Math.sin(a);this.bc([.213+.787*b+-.213*a,.715+-.715*b+-.715*a,.072+-.072*b+.928*a,0,0,.213+-.213*b+.143*a,.715+b*(1-.715)+
.14*a,.072+-.072*b+-.283*a,0,0,.213+-.213*b+-.787*a,.715+-.715*b+.715*a,.072+.928*b+.072*a,0,0,0,0,0,1,0,0,0,0,0,1])}};e.concat=function(a){return a=this.ki(a),a.length!=g.Ia?this:(this.bc(a),this)};e.clone=function(){return(new g).ga(this)};e.Jk=function(){for(var a=[],b=0,c=g.Ia;c>b;b++)a[b]=this[b];return a};e.ga=function(a){for(var b=g.Ia,c=0;b>c;c++)this[c]=a[c];return this};e.toString=function(){return"[ColorMatrix]"};e.bc=function(a){var b,c,d,f=[];for(b=0;5>b;b++){for(c=0;5>c;c++)f[c]=this[c+
5*b];for(c=0;5>c;c++){var h=0;for(d=0;5>d;d++)h+=a[c+5*d]*f[d];this[c+5*b]=h}}};e.Ec=function(a,b){return Math.min(b,Math.max(-b,a))};e.ki=function(a){return a instanceof g&&(a=a.Jk()),a.length<g.Ia?a=a.slice(0,a.length).concat(g.wd.slice(a.length,g.Ia)):a.length>g.Ia&&(a=a.slice(0,g.Ia)),a};createjs.al=g})();
(function(){function g(a){this.xc();this.l=a;this.gb="uniform mat4 uColorMatrix;uniform vec4 uColorMatrixOffset;void main(void) {vec4 color = texture2D(uSampler, vRenderCoord);mat4 m = uColorMatrix;vec4 newColor = vec4(0,0,0,0);newColor.r = color.r*m[0][0] + color.g*m[0][1] + color.b*m[0][2] + color.a*m[0][3];newColor.g = color.r*m[1][0] + color.g*m[1][1] + color.b*m[1][2] + color.a*m[1][3];newColor.b = color.r*m[2][0] + color.g*m[2][1] + color.b*m[2][2] + color.a*m[2][3];newColor.a = color.r*m[3][0] + color.g*m[3][1] + color.b*m[3][2] + color.a*m[3][3];gl_FragColor = newColor + uColorMatrixOffset;}"}var e=
createjs.extend(g,createjs.Mb);e.va=function(a,b,c){b=this.l;var d=new Float32Array([b[0],b[1],b[2],b[3],b[5],b[6],b[7],b[8],b[10],b[11],b[12],b[13],b[15],b[16],b[17],b[18]]);a.uniformMatrix4fv(a.getUniformLocation(c,"uColorMatrix"),!1,d);a.uniform4f(a.getUniformLocation(c,"uColorMatrixOffset"),b[4]/255,b[9]/255,b[14]/255,b[19]/255)};e.toString=function(){return"[ColorMatrixFilter]"};e.clone=function(){return new g(this.l)};e.jb=function(a){a=a.data;var b=a.length;var c=this.l;for(var d=c[0],f=c[1],
h=c[2],k=c[3],l=c[4],m=c[5],q=c[6],r=c[7],n=c[8],p=c[9],t=c[10],x=c[11],A=c[12],y=c[13],v=c[14],z=c[15],w=c[16],u=c[17],E=c[18],F=c[19],B=0;b>B;B+=4){c=a[B];var L=a[B+1];var K=a[B+2];var C=a[B+3];a[B]=c*d+L*f+K*h+C*k+l;a[B+1]=c*m+L*q+K*r+C*n+p;a[B+2]=c*t+L*x+K*A+C*y+v;a[B+3]=c*z+L*w+K*u+C*E+F}return!0};createjs.bl=createjs.C(g,"Filter")})();
(function(){function g(){throw"Touch cannot be instantiated";}g.bk=function(){return!!("ontouchstart"in window||window.navigator.msPointerEnabled&&0<window.navigator.msMaxTouchPoints||window.navigator.pointerEnabled&&0<window.navigator.maxTouchPoints)};g.enable=function(e,a,b){return e&&e.canvas&&g.bk()?e.I?!0:(e.I={Pe:{},fk:!a,preventDefault:!b,count:0},"ontouchstart"in window?g.Uh(e):(window.navigator.msPointerEnabled||window.navigator.pointerEnabled)&&g.Rh(e),!0):!1};g.disable=function(e){e&&("ontouchstart"in
window?g.Th(e):(window.navigator.msPointerEnabled||window.navigator.pointerEnabled)&&g.Qh(e),delete e.I)};g.Uh=function(e){var a=e.canvas,b=e.I.f=function(c){g.Vh(e,c)};a.addEventListener("touchstart",b,!1);a.addEventListener("touchmove",b,!1);a.addEventListener("touchend",b,!1);a.addEventListener("touchcancel",b,!1)};g.Th=function(e){var a=e.canvas;a&&(e=e.I.f,a.removeEventListener("touchstart",e,!1),a.removeEventListener("touchmove",e,!1),a.removeEventListener("touchend",e,!1),a.removeEventListener("touchcancel",
e,!1))};g.Vh=function(e,a){if(e){e.I.preventDefault&&a.preventDefault&&a.preventDefault();for(var b=a.changedTouches,c=a.type,d=0,f=b.length;f>d;d++){var h=b[d],k=h.identifier;h.target==e.canvas&&("touchstart"==c?this.Sf(e,k,a,h.pageX,h.pageY):"touchmove"==c?this.Rf(e,k,a,h.pageX,h.pageY):("touchend"==c||"touchcancel"==c)&&this.Qf(e,k,a))}}};g.Rh=function(e){var a=e.canvas,b=e.I.f=function(c){g.Sh(e,c)};void 0===window.navigator.pointerEnabled?(a.addEventListener("MSPointerDown",b,!1),window.addEventListener("MSPointerMove",
b,!1),window.addEventListener("MSPointerUp",b,!1),window.addEventListener("MSPointerCancel",b,!1),e.I.preventDefault&&(a.style.msTouchAction="none")):(a.addEventListener("pointerdown",b,!1),window.addEventListener("pointermove",b,!1),window.addEventListener("pointerup",b,!1),window.addEventListener("pointercancel",b,!1),e.I.preventDefault&&(a.style.touchAction="none"));e.I.fj={}};g.Qh=function(e){var a=e.I.f;void 0===window.navigator.pointerEnabled?(window.removeEventListener("MSPointerMove",a,!1),
window.removeEventListener("MSPointerUp",a,!1),window.removeEventListener("MSPointerCancel",a,!1),e.canvas&&e.canvas.removeEventListener("MSPointerDown",a,!1)):(window.removeEventListener("pointermove",a,!1),window.removeEventListener("pointerup",a,!1),window.removeEventListener("pointercancel",a,!1),e.canvas&&e.canvas.removeEventListener("pointerdown",a,!1))};g.Sh=function(e,a){if(e){e.I.preventDefault&&a.preventDefault&&a.preventDefault();var b=a.type,c=a.pointerId,d=e.I.fj;"MSPointerDown"==b||
"pointerdown"==b?a.srcElement==e.canvas&&(d[c]=!0,this.Sf(e,c,a,a.pageX,a.pageY)):d[c]&&("MSPointerMove"==b||"pointermove"==b?this.Rf(e,c,a,a.pageX,a.pageY):("MSPointerUp"==b||"MSPointerCancel"==b||"pointerup"==b||"pointercancel"==b)&&(delete d[c],this.Qf(e,c,a)))}};g.Sf=function(e,a,b,c,d){var f=e.I;if(f.fk||!f.count){var h=f.Pe;h[a]||(h[a]=!0,f.count++,e.Nd(a,b,c,d))}};g.Rf=function(e,a,b,c,d){e.I.Pe[a]&&e.Od(a,b,c,d)};g.Qf=function(e,a,b){var c=e.I,d=c.Pe;d[a]&&(c.count--,e.Pd(a,b,!0),delete d[a])};
createjs.Touch=g})();var M=createjs.sh=createjs.sh||{};M.version="1.0.0";M.rm="Thu, 14 Sep 2017 19:47:53 GMT";